Set-Content -Path .gitleaks.toml -NoNewline -Value @"
title = "Pocket Portfolio – Gitleaks config"

[allowlist]
# Only allow docs/fixtures; source code keeps scanning strict
paths = [
  '''^docs/''',
  '''^fixtures/''',
  '''^fixture/'''   # legacy path in history
]

# Benign/public tokens that often cause false positives
regexes = [
  # Firebase Web API keys are public identifiers
  '''AIza[0-9A-Za-z\-_]{35}''',

  # Obvious placeholders
  '''<YOUR_[A-Z0-9_]+>''',
  '''YOUR_[A-Z0-9_]+'''
]
"@
