blank_issues_enabled: false
contact_links:
  - name: 📣 Discussions — Ideas & Q&A
    url: https://github.com/hakeem22s/Financialprofilenetwork/discussions
    about: Ask questions or share ideas in Discussions.
