name: "💡 Feedback / Idea"
description: Share an idea or improvement for Pocket Portfolio.
title: "[Idea]: "
labels: [type/feature, status/needs-triage]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options: [tracking, prices, news, charts, mock-trading, auth, i18n, accessibility, other]
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What are you trying to do today that’s hard or impossible?
      placeholder: "I want to … but …"
  - type: textarea
    id: solution
    attributes:
      label: Idea
      description: What would a great solution look like?
  - type: input
    id: symbols
    attributes:
      label: Symbols (optional)
      description: Tickers or pairs (e.g., AAPL, BTC-USD, EUR-GBP)
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / mockups (optional)
  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      options:
        - label: I agree this feedback is public and contains no personal data.
          required: true
