/**
 * /designchallenge — Public landing for the Pocket Portfolio Design Partnership Challenge.
 *
 * Server-rendered. Sourced entirely from `lib/canonical-claims.ts` (DESIGN_CHALLENGE,
 * SDK, NUMBERS_SNAPSHOT, PERSON_ABBA, ORG, FOUNDER_CREDENTIALS_ABBA, MOAT_CLAIMS) so
 * copy on this surface stays aligned with /press, /llms.txt, and the challenge SSOT
 * markdown at docs/challenges/v1-regulated-verticals.md.
 *
 * Decision log (locked in planning):
 *   - Hero copy: CT1 H1 + CT2 eyebrow (merge).
 *   - GitHub primary: discussions/49 (founder must create thread before launch).
 *   - OG image: static /og/designchallenge.png (generated by build:challenge).
 *   - Founders Club: /sponsor?tier=founder; Enterprise: /sponsor.
 *   - No employer logo ribbon, no Annex III / cost-comparison copy in v1.
 */

import type { Metadata } from 'next';
import Link from 'next/link';
import { headers } from 'next/headers';
import { generateMetadata as genMeta } from '@/app/lib/seo/meta';
import ProductionNavbar from '@/app/components/marketing/ProductionNavbar';
import type { LiveSignal } from '@/app/press/jsonld';
import {
  BOARD_OF_INVESTORS,
  DESIGN_CHALLENGE,
  FOUNDER_CREDENTIALS_ABBA,
  MOAT_CLAIMS,
  NUMBERS_SNAPSHOT,
  ORG,
  PACKAGES,
  PERSON_ABBA,
  SDK,
  TIER1_DESIGN_PARTNER,
  URLS,
} from '@/lib/canonical-claims';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export const metadata: Metadata = genMeta({
  title: 'Design Partnership Challenge',
  description: `${DESIGN_CHALLENGE.eyebrow} ${DESIGN_CHALLENGE.subheadline}`,
  path: DESIGN_CHALLENGE.path,
  image: `${ORG.url}${DESIGN_CHALLENGE.ogImage}`,
});

/**
 * Border audit (2026-05): never use `--border-subtle` on large marketing CTAs — in
 * `[data-theme="light"]` it resolves to near-white on peach (`tokens.css`), which fails
 * contrast. Cards use a 1px amber hairline; **outline CTAs use 2px `var(--accent-warm)`**
 * (brand amber `#f59e0b`, CLAUDE.md) so the ring reads on light and dark surfaces.
 */
const COMMON_CARD: React.CSSProperties = {
  border: '1px solid var(--accent-warm)',
  borderRadius: '12px',
  padding: '20px',
  background: 'var(--surface)',
};

const MONO: React.CSSProperties = {
  fontFamily: 'var(--font-mono, ui-monospace, SFMono-Regular, monospace)',
};

/** GitHub-style outline (amber text, transparent fill). */
const ctaOutlineGitHub = (padding: string, fontSize: string): React.CSSProperties => ({
  border: '2px solid var(--accent-warm)',
  borderRadius: '10px',
  color: 'var(--accent-warm)',
  fontWeight: 700,
  padding,
  textDecoration: 'none',
  fontSize,
  background: 'transparent',
});

/** Community / CoderLegion tertiary — amber ring + body text + elevated surface (readable on peach). */
const ctaOutlineCommunity = (padding: string, fontSize: string): React.CSSProperties => ({
  border: '2px solid var(--accent-warm)',
  borderRadius: '10px',
  color: 'var(--text)',
  fontWeight: 600,
  padding,
  textDecoration: 'none',
  fontSize,
  background: 'var(--surface-elevated)',
});

function LdBlock({ data, id }: { data: unknown; id: string }) {
  return (
    <script
      id={id}
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

const SNAPSHOT_AGGREGATE_ROW = NUMBERS_SNAPSHOT.find((r) => r.numbersPackRowId === 'TRAC-01');

function snapshotFallback(): LiveSignal {
  return {
    totalDownloads:
      typeof SNAPSHOT_AGGREGATE_ROW?.value === 'number'
        ? (SNAPSHOT_AGGREGATE_ROW.value as number)
        : 9389,
    lastUpdated: SNAPSHOT_AGGREGATE_ROW?.asOf ?? '2026-04-20',
    source: 'snapshot',
  };
}

async function resolveNpmStatsUrl(): Promise<string> {
  try {
    const h = await headers();
    const host = h.get('x-forwarded-host') ?? h.get('host');
    const proto = h.get('x-forwarded-proto') ?? 'https';
    if (host) return `${proto}://${host}/api/npm-stats`;
  } catch {
    // headers() is only available inside a request scope; fall through.
  }
  return URLS.npmAggregateApi;
}

async function readLiveAggregate(): Promise<LiveSignal> {
  const fallback = snapshotFallback();
  try {
    const url = await resolveNpmStatsUrl();
    const res = await fetch(url, { cache: 'no-store' });
    if (!res.ok) return fallback;
    const data = (await res.json()) as { totalDownloads?: number; lastUpdated?: string };
    if (!data.totalDownloads || data.totalDownloads <= 0) return fallback;
    return {
      totalDownloads: data.totalDownloads,
      lastUpdated: data.lastUpdated ?? new Date().toISOString().slice(0, 10),
      source: 'live',
    };
  } catch {
    return fallback;
  }
}

const ENERGY_ASSETS_HIGHLIGHT = FOUNDER_CREDENTIALS_ABBA.highlights.find((h) =>
  h.includes('£7B')
) ?? '';

export default async function DesignChallengePage() {
  const live = await readLiveAggregate();
  const adapterFloor = SDK.brokerAdapterCount;
  const dataPointsLabel = '4.7B'; // PERSON_ABBA award copy mirrors NUMBERS-PACK FND-03.
  const energyAssetsLabel = '£7B';
  const moat = MOAT_CLAIMS.limitedScopeProcessor;

  const webPageLd = {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    '@id': `${DESIGN_CHALLENGE.url}#webpage`,
    url: DESIGN_CHALLENGE.url,
    name: `${DESIGN_CHALLENGE.headline} · Pocket Portfolio`,
    description: DESIGN_CHALLENGE.subheadline,
    isPartOf: { '@type': 'WebSite', '@id': `${ORG.url}#website`, url: ORG.url, name: ORG.name },
    primaryImageOfPage: {
      '@type': 'ImageObject',
      url: `${ORG.url}${DESIGN_CHALLENGE.ogImage}`,
      width: DESIGN_CHALLENGE.ogImageWidth,
      height: DESIGN_CHALLENGE.ogImageHeight,
    },
    breadcrumb: {
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: ORG.url },
        {
          '@type': 'ListItem',
          position: 2,
          name: 'Design Challenge',
          item: DESIGN_CHALLENGE.url,
        },
      ],
    },
  };

  const challengeLd = {
    '@context': 'https://schema.org',
    '@type': 'CreativeWork',
    '@id': `${DESIGN_CHALLENGE.url}#challenge`,
    name: DESIGN_CHALLENGE.headline,
    headline: DESIGN_CHALLENGE.headline,
    description: DESIGN_CHALLENGE.subheadline,
    url: DESIGN_CHALLENGE.url,
    inLanguage: 'en-GB',
    creator: { '@type': 'Organization', '@id': `${ORG.url}#organization`, name: ORG.name },
    publisher: { '@type': 'Organization', '@id': `${ORG.url}#organization`, name: ORG.name },
    audience: {
      '@type': 'Audience',
      audienceType:
        'AI architects, product designers, full-stack engineers, software engineers, and founders working in regulated verticals',
    },
    keywords: [
      'sovereign AI',
      'regulated AI',
      'limited-scope processor',
      'design partnership',
      'healthcare',
      'defense',
      'finance',
      'energy',
    ],
    mainEntityOfPage: DESIGN_CHALLENGE.url,
    sameAs: [DESIGN_CHALLENGE.github.submissionThread, DESIGN_CHALLENGE.coderLegionGroup],
  };

  return (
    <>
      <ProductionNavbar />

      <LdBlock id="ld-designchallenge-webpage" data={webPageLd} />
      <LdBlock id="ld-designchallenge" data={challengeLd} />

      <main
        style={{
          maxWidth: '1080px',
          margin: '0 auto',
          padding: 'clamp(24px, 5vw, 56px) clamp(16px, 4vw, 32px)',
          color: 'var(--text)',
        }}
      >
        <nav aria-label="Breadcrumb" style={{ marginBottom: '20px', fontSize: '14px' }}>
          <Link href="/" style={{ color: 'var(--text-secondary)', textDecoration: 'none' }}>
            Home
          </Link>
          <span style={{ margin: '0 8px', color: 'var(--text-secondary)' }}>/</span>
          <span style={{ color: 'var(--text)' }}>Design Challenge</span>
        </nav>

        {/* ───────────── Hero ───────────── */}
        <header style={{ marginBottom: 'clamp(32px, 5vw, 56px)' }}>
          <p
            style={{
              ...MONO,
              color: 'var(--accent-warm)',
              fontSize: '12px',
              letterSpacing: '0.14em',
              margin: '0 0 12px',
              textTransform: 'uppercase',
            }}
          >
            Design Partnership Challenge · v1 Regulated Verticals
          </p>
          <p
            style={{
              display: 'inline-block',
              border: '1px solid var(--accent-warm)',
              borderRadius: '999px',
              padding: '6px 14px',
              fontSize: '13px',
              fontWeight: 600,
              color: 'var(--accent-warm)',
              margin: '0 0 18px',
              ...MONO,
            }}
          >
            {DESIGN_CHALLENGE.eyebrow}
          </p>
          <h1
            style={{
              fontSize: 'clamp(30px, 4.8vw, 50px)',
              fontWeight: 800,
              lineHeight: 1.1,
              margin: '0 0 16px',
            }}
          >
            {DESIGN_CHALLENGE.headline}
          </h1>
          <p
            style={{
              fontSize: 'clamp(16px, 1.6vw, 19px)',
              color: 'var(--text-secondary)',
              margin: '0 0 24px',
              lineHeight: 1.6,
              maxWidth: '820px',
            }}
          >
            {DESIGN_CHALLENGE.subheadline}
          </p>

          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', marginBottom: '32px' }}>
            <a
              href={DESIGN_CHALLENGE.github.fork}
              rel="noopener noreferrer"
              target="_blank"
              style={{
                background: 'var(--accent-warm)',
                color: '#1a1208',
                fontWeight: 700,
                padding: '14px 22px',
                borderRadius: '10px',
                textDecoration: 'none',
                fontSize: '15px',
              }}
            >
              Fork the Substrate (GitHub)
            </a>
            <a
              href={DESIGN_CHALLENGE.github.submissionThread}
              rel="noopener noreferrer"
              target="_blank"
              style={ctaOutlineGitHub('14px 22px', '15px')}
            >
              Submit on GitHub Discussions →
            </a>
            <a
              href={DESIGN_CHALLENGE.coderLegionGroup}
              rel="noopener noreferrer"
              target="_blank"
              style={ctaOutlineCommunity('14px 22px', '15px')}
            >
              Join Open-Fi Builders (CoderLegion)
            </a>
          </div>

          <figure
            style={{
              ...COMMON_CARD,
              padding: 0,
              overflow: 'hidden',
              borderColor: 'var(--accent-warm)',
            }}
          >
            <div style={{ background: '#f8fafc', padding: '20px' }}>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="/book-assets/figures/si-figure-02-hybrid-architecture.svg"
                alt="Pocket Portfolio hybrid architecture: in-browser ingestion, local-first storage, stateless AI inference. The limited-scope processor boundary separates user-controlled data from the inference plane."
                style={{ width: '100%', height: 'auto', display: 'block' }}
              />
            </div>
            <figcaption
              style={{
                padding: '14px 18px',
                fontSize: '13px',
                color: 'var(--text-secondary)',
                background: 'var(--surface)',
                borderTop: '1px solid var(--accent-warm)',
              }}
            >
              <strong style={{ color: 'var(--text)' }}>Figure 2 · Hybrid Architecture.</strong>{' '}
              {moat.longForm}
            </figcaption>
          </figure>
        </header>

        {/* ───────────── Stats strip ───────────── */}
        <section
          aria-label="Substrate evidence"
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
            gap: '14px',
            marginBottom: 'clamp(32px, 5vw, 56px)',
          }}
        >
          {(
            [
              {
                value: `${adapterFloor}+`,
                label: `Broker adapters · @pocket-portfolio/importer ${SDK.license}`,
              },
              { value: dataPointsLabel, label: 'Data points · Whale Watch (DataIQ ESG 2024)' },
              { value: energyAssetsLabel, label: 'Energy assets supported · decision platform' },
              {
                value: live.totalDownloads.toLocaleString(),
                label: `Aggregate npm downloads · ${PACKAGES.length} @pocket-portfolio/* packages`,
                hint:
                  live.source === 'live'
                    ? `Live npm API · observed ${live.lastUpdated}`
                    : `Frozen snapshot · as of ${live.lastUpdated}`,
              },
            ] as const
          ).map((tile) => (
            <div key={tile.label} style={COMMON_CARD}>
              <p
                style={{
                  ...MONO,
                  margin: '0 0 6px',
                  fontSize: '28px',
                  fontWeight: 800,
                  color: 'var(--accent-warm)',
                }}
              >
                {tile.value}
              </p>
              <p style={{ margin: 0, fontSize: '12px', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                {tile.label}
              </p>
              {'hint' in tile ? (
                <p
                  style={{
                    margin: '6px 0 0',
                    fontSize: '11px',
                    color: 'var(--text-secondary)',
                    opacity: 0.85,
                    ...MONO,
                  }}
                >
                  {tile.hint}
                </p>
              ) : null}
            </div>
          ))}
        </section>

        {/* ───────────── Four pillars ───────────── */}
        <section style={{ marginBottom: 'clamp(32px, 5vw, 56px)' }}>
          <h2 style={{ fontSize: 'clamp(22px, 2.5vw, 28px)', fontWeight: 800, margin: '0 0 18px' }}>
            Why this challenge exists
          </h2>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
              gap: '14px',
            }}
          >
            <article style={COMMON_CARD}>
              <h3 style={{ margin: '0 0 8px', fontSize: '17px', fontWeight: 700 }}>Why</h3>
              <p style={{ margin: 0, fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                Regulated AI deployments stall on data gravity. The {moat.phrase} posture
                reduces the audit perimeter (GDPR Art. 5(1)(c) data-minimisation) and gives
                vertical operators a defensible architectural starting point — not a policy
                promise.
              </p>
            </article>
            <article style={COMMON_CARD}>
              <h3 style={{ margin: '0 0 8px', fontSize: '17px', fontWeight: 700 }}>How</h3>
              <p style={{ margin: 0, fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                Fork the {SDK.license}-licensed substrate. Adapt the {adapterFloor}+ broker
                adapter pattern to your vertical&apos;s primary data formats. Run inference
                stateless. Submit your fork + strategy + prototype on{' '}
                <a
                  href={DESIGN_CHALLENGE.github.importerTree}
                  rel="noopener noreferrer"
                  target="_blank"
                  style={{ color: 'var(--accent-warm)', textDecoration: 'none' }}
                >
                  GitHub
                </a>
                .
              </p>
            </article>
            <article style={COMMON_CARD}>
              <h3 style={{ margin: '0 0 8px', fontSize: '17px', fontWeight: 700 }}>Rewards</h3>
              <ul
                style={{
                  margin: 0,
                  paddingLeft: '18px',
                  fontSize: '14px',
                  color: 'var(--text-secondary)',
                  lineHeight: 1.6,
                }}
              >
                {DESIGN_CHALLENGE.rewards.map((r) => (
                  <li key={r} style={{ marginBottom: '6px' }}>
                    {r}
                  </li>
                ))}
              </ul>
              <p style={{ margin: '12px 0 0', fontSize: '13px' }}>
                <Link
                  href="/sponsor?tier=founder"
                  style={{ color: 'var(--accent-warm)', textDecoration: 'none', fontWeight: 600 }}
                >
                  Founders Club →
                </Link>
                <span style={{ margin: '0 8px', color: 'var(--text-secondary)' }}>·</span>
                <Link
                  href="/sponsor"
                  style={{ color: 'var(--accent-warm)', textDecoration: 'none', fontWeight: 600 }}
                >
                  Enterprise sponsorship →
                </Link>
              </p>
            </article>
            <article style={COMMON_CARD}>
              <h3 style={{ margin: '0 0 8px', fontSize: '17px', fontWeight: 700 }}>Authority</h3>
              <p
                style={{
                  margin: '0 0 8px',
                  fontSize: '14px',
                  color: 'var(--text-secondary)',
                  lineHeight: 1.6,
                }}
              >
                Curated by {PERSON_ABBA.name} ({PERSON_ABBA.jobTitle}). Receipts: 2024 DataIQ
                ESG Award contributor (4.7B data points), {energyAssetsLabel} energy-assets
                decision platform, UK Black Business Show 2024 speaker.
              </p>
              <p style={{ margin: 0, fontSize: '13px' }}>
                <Link
                  href="/press/abba-lawal"
                  style={{ color: 'var(--accent-warm)', textDecoration: 'none', fontWeight: 600 }}
                >
                  Founder profile →
                </Link>
                <span style={{ margin: '0 8px', color: 'var(--text-secondary)' }}>·</span>
                <Link
                  href="/press"
                  style={{ color: 'var(--accent-warm)', textDecoration: 'none', fontWeight: 600 }}
                >
                  Press kit →
                </Link>
              </p>
            </article>
          </div>
        </section>

        {/* ───────────── Vertical cards ───────────── */}
        <section style={{ marginBottom: 'clamp(32px, 5vw, 56px)' }}>
          <h2 style={{ fontSize: 'clamp(22px, 2.5vw, 28px)', fontWeight: 800, margin: '0 0 8px' }}>
            Choose your vertical
          </h2>
          <p
            style={{
              margin: '0 0 18px',
              fontSize: '14px',
              color: 'var(--text-secondary)',
              maxWidth: '760px',
            }}
          >
            Submissions are open for any regulated vertical; the four below are the v1 cohort.
            {ENERGY_ASSETS_HIGHLIGHT
              ? ' The Energy reference draws on a £7B asset platform delivery.'
              : ''}
          </p>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
              gap: '14px',
            }}
          >
            {DESIGN_CHALLENGE.verticals.map((v) => (
              <article key={v.id} style={COMMON_CARD}>
                <p
                  style={{
                    ...MONO,
                    margin: '0 0 8px',
                    fontSize: '11px',
                    letterSpacing: '0.14em',
                    textTransform: 'uppercase',
                    color: 'var(--accent-warm)',
                  }}
                >
                  Vertical
                </p>
                <h3 style={{ margin: '0 0 8px', fontSize: '18px', fontWeight: 700 }}>{v.label}</h3>
                <p
                  style={{
                    margin: 0,
                    fontSize: '14px',
                    color: 'var(--text-secondary)',
                    lineHeight: 1.6,
                  }}
                >
                  {v.blurb}
                </p>
              </article>
            ))}
          </div>
        </section>

        {/* ───────────── Submission artefacts ───────────── */}
        <section style={{ marginBottom: 'clamp(32px, 5vw, 56px)' }}>
          <h2 style={{ fontSize: 'clamp(22px, 2.5vw, 28px)', fontWeight: 800, margin: '0 0 14px' }}>
            What to submit
          </h2>
          <ol
            style={{
              margin: 0,
              paddingLeft: '20px',
              fontSize: '15px',
              lineHeight: 1.7,
              color: 'var(--text)',
            }}
          >
            {DESIGN_CHALLENGE.artefacts.map((a) => (
              <li key={a} style={{ marginBottom: '6px' }}>
                {a}
              </li>
            ))}
          </ol>
          <p style={{ margin: '14px 0 0', fontSize: '14px', color: 'var(--text-secondary)' }}>
            Reviews are open and on-thread by the Pocket Portfolio advisory committee and early
            users.
          </p>
        </section>

        {/* ───────────── Multi-channel conversion ───────────── */}
        <section style={{ marginBottom: 'clamp(32px, 5vw, 56px)' }}>
          <h2 style={{ fontSize: 'clamp(22px, 2.5vw, 28px)', fontWeight: 800, margin: '0 0 14px' }}>
            Two paths in
          </h2>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
              gap: '14px',
            }}
          >
            <article style={{ ...COMMON_CARD, background: 'var(--surface)' }}>
              <p
                style={{
                  ...MONO,
                  margin: '0 0 6px',
                  fontSize: '11px',
                  letterSpacing: '0.14em',
                  textTransform: 'uppercase',
                  color: 'var(--accent-warm)',
                }}
              >
                Architect path
              </p>
              <h3 style={{ margin: '0 0 8px', fontSize: '18px', fontWeight: 700 }}>
                GitHub Discussions
              </h3>
              <p
                style={{
                  margin: '0 0 14px',
                  fontSize: '14px',
                  color: 'var(--text-secondary)',
                  lineHeight: 1.6,
                }}
              >
                For builders ready to ship code, strategy docs, and prototypes. Submit fork
                links, PDFs, or hosted URLs on the discussion thread.
              </p>
              <a
                href={DESIGN_CHALLENGE.github.submissionThread}
                rel="noopener noreferrer"
                target="_blank"
                style={{
                  background: 'var(--accent-warm)',
                  color: '#1a1208',
                  fontWeight: 700,
                  padding: '12px 18px',
                  borderRadius: '10px',
                  textDecoration: 'none',
                  fontSize: '14px',
                  display: 'inline-block',
                }}
              >
                Open submission thread →
              </a>
            </article>
            <article style={{ ...COMMON_CARD, background: 'var(--surface)' }}>
              <p
                style={{
                  ...MONO,
                  margin: '0 0 6px',
                  fontSize: '11px',
                  letterSpacing: '0.14em',
                  textTransform: 'uppercase',
                  color: 'var(--accent-warm)',
                }}
              >
                Community path
              </p>
              <h3 style={{ margin: '0 0 8px', fontSize: '18px', fontWeight: 700 }}>
                CoderLegion · Open-Fi Builders
              </h3>
              <p
                style={{
                  margin: '0 0 14px',
                  fontSize: '14px',
                  color: 'var(--text-secondary)',
                  lineHeight: 1.6,
                }}
              >
                For vertical founders, designers, and product strategists focused on UX flows
                and regulatory framing. Coordinated cohort push: 2026-05-11, 08:45 GMT.
              </p>
              <a
                href={DESIGN_CHALLENGE.coderLegionGroup}
                rel="noopener noreferrer"
                target="_blank"
                style={{ ...ctaOutlineGitHub('12px 18px', '14px'), display: 'inline-block' }}
              >
                Join the cohort →
              </a>
            </article>
          </div>
        </section>

        {/* ───────────── Tier 1 escalation ───────────── */}
        <section style={{ marginBottom: 'clamp(32px, 5vw, 56px)' }}>
          <h2 style={{ fontSize: 'clamp(22px, 2.5vw, 28px)', fontWeight: 800, margin: '0 0 14px' }}>
            Tier 1 escalation
          </h2>
          <p style={{ margin: '0 0 14px', fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
            If you are already operating inside a regulated institution, these are the high-intent surfaces: the Tier 1 technical brief and the seed governance board.
          </p>
          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
            <Link
              href={TIER1_DESIGN_PARTNER.path}
              style={{
                background: 'var(--accent-warm)',
                color: '#1a1208',
                fontWeight: 800,
                padding: '12px 18px',
                borderRadius: '10px',
                textDecoration: 'none',
                fontSize: '14px',
              }}
            >
              {TIER1_DESIGN_PARTNER.eyebrow} →
            </Link>
            <Link
              href={BOARD_OF_INVESTORS.path}
              style={{ ...ctaOutlineCommunity('12px 18px', '14px'), display: 'inline-block' }}
            >
              {BOARD_OF_INVESTORS.eyebrow} (max {BOARD_OF_INVESTORS.maxSeats}) →
            </Link>
          </div>
        </section>

        {/* ───────────── Closing CTA ───────────── */}
        <section
          aria-label="Closing call to action"
          style={{
            ...COMMON_CARD,
            display: 'flex',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
            alignItems: 'center',
            gap: '16px',
            background: 'var(--background)',
          }}
        >
          <div style={{ flex: '1 1 320px' }}>
            <p style={{ margin: '0 0 6px', fontSize: '13px', color: 'var(--accent-warm)', ...MONO, letterSpacing: '0.12em', textTransform: 'uppercase' }}>
              Build for purpose. Verify on artifact. Reciprocate the signal.
            </p>
            <p style={{ margin: 0, fontSize: '15px', color: 'var(--text-secondary)' }}>
              The substrate is open. Receipts are dated. The verticals are yours to shape.
            </p>
          </div>
          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
            <a
              href={DESIGN_CHALLENGE.github.fork}
              rel="noopener noreferrer"
              target="_blank"
              style={{
                background: 'var(--accent-warm)',
                color: '#1a1208',
                fontWeight: 700,
                padding: '12px 18px',
                borderRadius: '10px',
                textDecoration: 'none',
                fontSize: '14px',
              }}
            >
              Fork the Substrate
            </a>
            <a
              href={DESIGN_CHALLENGE.coderLegionGroup}
              rel="noopener noreferrer"
              target="_blank"
              style={{ ...ctaOutlineGitHub('12px 18px', '14px') }}
            >
              CoderLegion
            </a>
          </div>
        </section>
      </main>
    </>
  );
}
