/**
 * Plate cache-bust tokens — auto-generated by npm run sync:open-web-plates
 * Do not edit by hand.
 */
export const OPEN_LANDING_PLATE_CACHE: Record<string, string> = {
  'web-hero-glass-vault.png': '1db1a7b11bc5',
  'web-boundary-split-brain.png': '6899a78c914b',
  'web-boundary-frontier.png': '5181509ba0a7',
  'web-traction-dual-pane.png': 'ee258932a851',
  'web-traction-heatmap.png': '83b9d6ce7db0',
  'web-split-brain-pillars.png': '4feb58258e91',
  'web-substrate-matrix.png': '89d20f3eb903',
  'web-clean-room-console.png': '8e7d994884a6',
};

/** Public plate URL with content hash — busts Next.js image optimizer cache after sync. */
export function plateSrc(filename: string): string {
  const token = OPEN_LANDING_PLATE_CACHE[filename];
  const base = `/open/landing/plates/${filename}`;
  return token ? `${base}?v=${token}` : base;
}
