/**
 * Plate cache-bust tokens — auto-generated by npm run sync:open-web-plates
 * Do not edit by hand.
 */
export const OPEN_LANDING_PLATE_CACHE: Record<string, string> = {
  'web-hero-glass-vault.png': '0b899db535d7',
  'web-boundary-split-brain.png': '61d0790f1ef2',
  'web-boundary-frontier.png': '8c8111a9acbf',
  'web-traction-dual-pane.png': '1d9777d4199c',
  'web-traction-heatmap.png': '37ea90ec7af2',
  'web-split-brain-pillars.png': '1d8f7bcaa47f',
  'web-substrate-matrix.png': 'ed4ad104e74c',
  'web-clean-room-console.png': '097589ae9e20',
};

/** Public plate URL with content hash — busts Next.js image optimizer cache after sync. */
export function plateSrc(filename: string): string {
  const token = OPEN_LANDING_PLATE_CACHE[filename];
  const base = `/open/landing/plates/${filename}`;
  return token ? `${base}?v=${token}` : base;
}
