/**
 * Auto-generated by scripts/sync-pocket-web-plates.mjs — do not edit by hand.
 * Run: npm run sync:pocket-web-plates
 */

export const POCKET_LANDING_PLATE_CACHE: Record<string, string> = {
  'web-portal-terminal.png': 'b678aad96445',
  'web-portal-storage.png': '0b443fdf4a64',
  'web-portal-founders.png': '5946e7bf1683',
  'web-why-choose.png': '2d30293746b3',
  'web-ad-free-invariant.png': '265a048bcd23',
  'web-fin-pillars.png': 'ca76ff14699a',
  'web-community-nodes.png': '600f9b8ac611',
  'web-news-regulatory.png': '6e6c38b8700b',
  'web-news-infra.png': 'bd9956627516',
  'web-news-wealth-tech.png': 'e42f979dcaa6',
  'web-news-market.png': 'e521f3d4887e',
};

export function plateSrc(filename: string): string {
  const token = POCKET_LANDING_PLATE_CACHE[filename];
  const base = `/pocket/landing/plates/${filename}`;
  return token ? `${base}?v=${token}` : base;
}
