/**
 * Auto-generated by scripts/sync-pocket-web-plates.mjs — do not edit by hand.
 * Run: npm run sync:pocket-web-plates
 */

export const POCKET_LANDING_PLATE_CACHE: Record<string, string> = {
  'web-portal-terminal.png': '6ded4d6b0d84',
  'web-portal-storage.png': '1497a99b1eb3',
  'web-portal-founders.png': '861475a13b6e',
  'web-why-choose.png': '7df657ad3bdb',
  'web-ad-free-invariant.png': 'ebd3d156eefe',
  'web-fin-pillars.png': '8246a709780f',
  'web-community-nodes.png': '476c62601a9c',
  'web-news-regulatory.png': '2cbcf7373335',
  'web-news-infra.png': 'b6da3bad6624',
  'web-news-wealth-tech.png': 'a4a8b2a243de',
  'web-news-market.png': '5c4ada3d3657',
};

export function plateSrc(filename: string): string {
  const token = POCKET_LANDING_PLATE_CACHE[filename];
  const base = `/pocket/landing/plates/${filename}`;
  return token ? `${base}?v=${token}` : base;
}
