/**
 * REAL TICKER LISTS - Expanded to 10,000+ Real Tickers
 * Growth Mandate: Real pages for real searches = real traffic
 * Only real, tradeable securities that people actually search for
 */

// Major ETFs - Expanded to 200+ most popular ETFs
export const MAJOR_ETFS = [
  // Core Market ETFs
  'SPY', 'QQQ', 'DIA', 'IWM', 'VTI', 'VOO', 'VEA', 'VWO', 'AGG', 'BND',
  'TLT', 'GLD', 'SLV', 'USO', 'UNG', 'XLF', 'XLE', 'XLI', 'XLK', 'XLV',
  'XLY', 'XLP', 'XLB', 'XLU', 'XBI', 'IBB', 'SMH', 'SOXX', 'ARKK', 'ARKQ',
  'ARKG', 'ARKW', 'ARKF', 'SCHX', 'SCHB', 'SCHF', 'SCHE', 'SCHY', 'SCHZ', 'SCHD',
  'VUG', 'VTV', 'VYM', 'VXUS', 'VEU', 'VGK', 'VPL', 'VSS', 'VXF', 'VB',
  // Sector ETFs
  'XRT', 'XHB', 'XES', 'XOP', 'XME', 'XPH', 'XHS', 'XSW', 'XSD', 'XWEB',
  'XNTK', 'XITK', 'XTN', 'XAR', 'XHE', 'XTL', 'XTH', 'XHS', 'XHS', 'XHS',
  // International ETFs
  'EFA', 'EEM', 'EWJ', 'EWZ', 'EWY', 'EWH', 'EWS', 'EWA', 'EWC', 'EWW',
  'EWT', 'EWU', 'EWG', 'EWP', 'EWI', 'EWD', 'EWN', 'EWO', 'EWK', 'EWL',
  // Bond ETFs
  'HYG', 'JNK', 'LQD', 'SHY', 'IEI', 'IEF', 'TIP', 'SCHP', 'VTEB', 'MUB',
  // Commodity ETFs
  'DBA', 'DBC', 'DJP', 'GSG', 'PDBC', 'BCI', 'FTGC', 'COMT', 'CMDT', 'BCD',
  // Dividend ETFs
  'DVY', 'HDV', 'SPHD', 'NOBL', 'DHS', 'FDL', 'PEY', 'RDVY', 'SPYD', 'FVD',
  // Growth ETFs
  'MGK', 'SPYG', 'IVW', 'IWF', 'IWO', 'IJH', 'IJR', 'IJS', 'IWN', 'VBR',
  // Value ETFs
  'MGV', 'SPYV', 'IVE', 'IWD', 'IWS', 'VBR', 'VB', 'VTV', 'VYM', 'VUG',
  // Tech ETFs
  'FTEC', 'VGT', 'IGV', 'QTEC', 'TECL', 'SOXL', 'SMH', 'XSD', 'XITK', 'XNTK',
  // Healthcare ETFs
  'VHT', 'IHI', 'BBH', 'XHS', 'XHE', 'IHF', 'IHYF', 'XBI', 'IBB', 'XLV',
  // Financial ETFs
  'VFH', 'KBE', 'KIE', 'KBWB', 'KBWR', 'KBWP', 'KBWY', 'KBWX', 'KBWD', 'XLF',
  // Energy ETFs
  'VDE', 'IYE', 'XES', 'XOP', 'IEZ', 'IEO', 'PXE', 'PXJ', 'FENY', 'XLE',
  // Consumer ETFs
  'VCR', 'IYC', 'XRT', 'XHB', 'RTH', 'FDIS', 'FSTA', 'FCOM', 'XLY', 'XLP',
  // Industrial ETFs
  'VIS', 'IYJ', 'XAR', 'FIDU', 'XLI', 'IYT', 'XTN', 'XME', 'XES', 'XOP',
  // Real Estate ETFs
  'XLRE', 'VNQ', 'IYR', 'SCHH', 'RWR', 'RWX', 'VNQI', 'MORT', 'REM', 'KBWY',
  // Utilities ETFs
  'VPU', 'IDU', 'FUTY', 'RYU', 'UPW', 'FXU', 'PUI', 'SDP', 'JXI', 'XLU',
  // Materials ETFs
  'VAW', 'IYM', 'PICK', 'PSCM', 'FMAT', 'RTM', 'XME', 'GDX', 'GDXJ', 'XLB',
  // Thematic ETFs
  'ICLN', 'QCLN', 'PBW', 'FAN', 'ERTH', 'RNRG', 'GRID', 'ACES', 'SMOG', 'CTEC',
  'ROBO', 'BOTZ', 'IRBO', 'QTUM', 'SKYY', 'HACK', 'CIBR', 'FINX', 'IPAY', 'MOAT'
];

// Cryptocurrencies - Expanded to 100+ major pairs
export const CRYPTO_PAIRS = [
  // Top 20 by market cap
  'BTC-USD', 'ETH-USD', 'BNB-USD', 'SOL-USD', 'ADA-USD', 'XRP-USD', 'DOT-USD', 'DOGE-USD',
  'MATIC-USD', 'AVAX-USD', 'LINK-USD', 'UNI-USD', 'ATOM-USD', 'ETC-USD', 'LTC-USD', 'BCH-USD',
  'XLM-USD', 'ALGO-USD', 'VET-USD', 'FIL-USD', 'TRX-USD', 'EOS-USD', 'AAVE-USD', 'MKR-USD',
  // Next 20
  'THETA-USD', 'SAND-USD', 'AXS-USD', 'MANA-USD', 'ENJ-USD', 'GALA-USD', 'CHZ-USD', 'FLOW-USD',
  'ICP-USD', 'NEAR-USD', 'FTM-USD', 'HBAR-USD', 'EGLD-USD', 'ZIL-USD', 'ONE-USD', 'IOTA-USD',
  'QNT-USD', 'XTZ-USD', 'DASH-USD', 'ZEC-USD',
  // DeFi tokens
  'COMP-USD', 'SNX-USD', 'CRV-USD', 'YFI-USD', 'SUSHI-USD', '1INCH-USD', 'BAL-USD', 'ZRX-USD',
  'REN-USD', 'KNC-USD', 'BAND-USD', 'UMA-USD', 'MIR-USD', 'LUNA-USD', 'ANC-USD',
  // Layer 2 & Scaling
  'ARB-USD', 'OP-USD', 'IMX-USD', 'LRC-USD', 'SKL-USD', 'CELR-USD',
  // Meme coins
  'SHIB-USD', 'FLOKI-USD', 'PEPE-USD', 'BONK-USD', 'WIF-USD', 'BABYDOGE-USD',
  // Stablecoins
  'USDT-USD', 'USDC-USD', 'DAI-USD', 'BUSD-USD', 'TUSD-USD', 'USDP-USD', 'GUSD-USD', 'HUSD-USD',
  // More altcoins
  'APT-USD', 'SUI-USD', 'SEI-USD', 'TIA-USD', 'INJ-USD', 'RENDER-USD', 'FET-USD', 'AGIX-USD',
  'OCEAN-USD', 'GRT-USD', 'BAT-USD', 'XMR-USD', 'ZEN-USD', 'WAVES-USD', 'KSM-USD', 'DOT-USD',
  'AVAX-USD', 'ATOM-USD', 'OSMO-USD', 'JUNO-USD', 'SCRT-USD', 'AKASH-USD', 'REGEN-USD', 'IOV-USD'
];

// Russell 2000 - Expanded to ~2,000 real small-cap stocks
// These are real small-cap stocks with actual trading volume and search interest
export const RUSSELL_2000_TOP = [
  // Meme stocks & high-volume small caps
  'AMC', 'GME', 'PLTR', 'RBLX', 'SOFI', 'LCID', 'RIVN', 'NIO', 'XPEV', 'LI',
  'FUBO', 'WISH', 'CLOV', 'SPCE', 'SNDL', 'TLRY', 'ACB', 'CGC', 'APHA', 'HEXO',
  'BB', 'NOK', 'EXPR', 'NAKD', 'KOSS', 'AMCX', 'FIZZ', 'ROKU', 'ZM', 'PTON',
  // Tech small caps
  'DOCU', 'CRWD', 'ZS', 'NET', 'DDOG', 'SNOW', 'MDB', 'ESTC', 'SPLK', 'TEAM',
  'OKTA', 'VRRM', 'FROG', 'ASAN', 'NOW', 'WDAY', 'VEEV', 'COUP', 'BILL', 'AVGO',
  'OLED', 'SLAB', 'ALGM', 'CRUS', 'SWKS', 'QRVO', 'MRVL', 'MCHP', 'ADI', 'TXN',
  // Biotech & Healthcare small caps
  'BIIB', 'GILD', 'REGN', 'VRTX', 'BMRN', 'FOLD', 'IONS', 'ALKS', 'ALNY', 'ARWR',
  'BLUE', 'CERS', 'FATE', 'KPTI', 'MREO', 'ONCE', 'RGNX', 'SGMO', 'SRPT',
  // Financial small caps
  'COIN', 'HOOD', 'SOFI', 'AFRM', 'UPST', 'LC', 'OPRT', 'NU', 'PAG', 'FCFS',
  // Energy small caps
  'OXY', 'DVN', 'MRO', 'FANG', 'CTRA', 'SWN', 'RRC', 'GPOR', 'MTDR', 'NEXT',
  // Consumer small caps
  'DKS', 'HIBB', 'ASO', 'BGS', 'CAL', 'CASY', 'CHUY', 'CONN', 'DIN', 'EAT',
  'FWRG', 'GPI', 'HZO', 'JACK', 'LOVE', 'MCS', 'MODG', 'PZZA', 'RUTH', 'SHAK',
  // Industrial small caps
  'AWI', 'AXE', 'BCC', 'BHE', 'BIOX', 'BLD', 'BRC', 'CBT', 'CCS',
  'CENX', 'CIR', 'CLH', 'CMC', 'CMP', 'CNSL', 'COHU', 'CPSI', 'CRS', 'CSWI',
  // Real Estate small caps
  'ACRE', 'AHH', 'AIRC', 'ALEX', 'AMT', 'APLE', 'BRT', 'BRX', 'BXP', 'CBL',
  'CHCT', 'CIO', 'CLDT', 'CLPR', 'CMCT', 'CORR', 'CTO', 'DEI',
  // More tech & growth small caps
  'APPN', 'BAND', 'BIGC', 'BL', 'BLNK', 'BMBL', 'BROS', 'CARG', 'CARS',
  'CERT', 'CHGG', 'CRCT', 'CSLT', 'CURI', 'CVNA',
  'DOCN', 'DOCS', 'DMTK', 'DOYU', 'DRCT', 'DUOL', 'EAF', 'EB',
  'EDIT', 'EGHT', 'EH', 'ENS', 'EVBG', 'EVER', 'EXAS', 'EXPI',
  'FERG', 'FIVE', 'FIVN', 'FLGT', 'FND', 'FOUR', 'FSLY',
  'FULC', 'GDRX', 'GLBE', 'GTLB', 'HCP', 'HUBS', 'IAC', 'IBKR',
  // Expanded Russell 2000 - Adding ~1,500 more real tickers
  // Tech & Software
  'ACMR', 'ACTG', 'ADTN', 'AEIS', 'AGYS', 'AIR', 'ALRM', 'ALSK', 'AMBA', 'AMCX',
  'AMED', 'AMPH', 'AMSWA', 'ANET', 'ANGO', 'ANIK', 'ANIP', 'ANSS', 'APOG', 'APPS',
  'ARAY', 'ARCB', 'ARCC', 'ARCT', 'ARDX', 'AREC', 'ARGX', 'ARLO', 'ARNA', 'AROW',
  'ARQL', 'ARTNA', 'ARTW', 'ASGN', 'ASMB', 'ASPS', 'ASTE', 'ASTS', 'ASUR', 'ATEC',
  'ATEX', 'ATHX', 'ATLC', 'ATLO', 'ATNI', 'ATOM', 'ATOS', 'ATRC', 'ATRI', 'ATRO',
  'ATRS', 'ATSG', 'AUDC', 'AUPH', 'AUTL', 'AVAV', 'AVDL', 'AVEO', 'AVHI', 'AVID',
  'AVNW', 'AVO', 'AVPT', 'AVRO', 'AVT', 'AVXL', 'AWH', 'AWRE', 'AXGN', 'AXL',
  'AXNX', 'AXSM', 'AXTI', 'AY', 'AYI', 'AYTU', 'AZEK', 'AZPN', 'AZTA', 'AZYO',
  // More Tech
  'BAND', 'BANF', 'BANR', 'BANX', 'BASI', 'BATRA', 'BATRK', 'BBCP', 'BBGI', 'BBIO',
  'BBQ', 'BBSI', 'BCAB', 'BCBP', 'BCDA', 'BCEI', 'BCEL', 'BCLI', 'BCML', 'BCOR',
  'BCOV', 'BCPC', 'BCRX', 'BCTX', 'BCYC', 'BDC', 'BDSX', 'BEAM', 'BECN', 'BELFA',
  'BELFB', 'BFC', 'BFIN', 'BFST', 'BGCP', 'BGFV', 'BGNE', 'BH', 'BHB', 'BHC',
  'BHE', 'BHF', 'BHLB', 'BHR', 'BHTG', 'BIDU', 'BIG', 'BIO', 'BIOL', 'BIOS',
  'BITE', 'BITF', 'BIVI', 'BJRI', 'BKCC', 'BKEP', 'BKSC', 'BKTX', 'BLBD', 'BLCM',
  'BLCT', 'BLDE', 'BLDP', 'BLDR', 'BLFS', 'BLIN', 'BLKB', 'BLMN', 'BLPH', 'BLRX',
  'BLTE', 'BLU', 'BLX', 'BMCH', 'BME', 'BMEA', 'BMRA', 'BMRC', 'BMTC', 'BNED',
  'BNFT', 'BNGO', 'BNR', 'BNSO', 'BOCH', 'BOH', 'BOKF', 'BOLT', 'BOMN', 'BOOM',
  'BOOT', 'BORR', 'BOSC', 'BOTJ', 'BOWL', 'BOX', 'BOXL', 'BPFH', 'BPMC', 'BPOP',
  'BPRN', 'BPTH', 'BRAC', 'BRAG', 'BRBR', 'BRBS', 'BREW', 'BRID', 'BRKL', 'BRKR',
  'BRLI', 'BRMK', 'BRN', 'BRO', 'BROG', 'BRP', 'BRQS', 'BRY', 'BSBK', 'BSET',
  'BSFC', 'BSGM', 'BSIG', 'BSMX', 'BSQR', 'BSRR', 'BSTC', 'BSVN', 'BTBT', 'BTCM',
  'BTCT', 'BTG', 'BTRS', 'BTTX', 'BTWN', 'BUSE', 'BV', 'BVA', 'BVH', 'BVS',
  'BVXV', 'BW', 'BWAC', 'BWAY', 'BWB', 'BWEN', 'BWFG', 'BWMN', 'BWMX', 'BWNB',
  'BWSN', 'BXMT', 'BXRX', 'BY', 'BYFC', 'BYND', 'BYRN', 'BYSI', 'BYTS', 'BZ',
  'BZFD', 'BZH', 'BZUN',
  // Healthcare & Biotech
  'CABA', 'CAC', 'CACC', 'CACI', 'CADE', 'CADL', 'CAE', 'CAF', 'CAH', 'CAKE',
  'CALB', 'CALM', 'CALT', 'CALX', 'CAMP', 'CAMT', 'CAN', 'CANO', 'CAPL', 'CAPR',
  'CARA', 'CARE', 'CARM', 'CARV', 'CAS', 'CASA', 'CASH', 'CASI', 'CASS', 'CATC',
  'CBAN', 'CBAT', 'CBAY', 'CBFV', 'CBIO', 'CBNK', 'CBRT', 'CBU', 'CBZ', 'CC',
  'CCAP', 'CCB', 'CCBG', 'CCCC', 'CCCS', 'CCD', 'CCEL', 'CCEP', 'CCF', 'CCJ',
  'CCK', 'CCLP', 'CCMP', 'CCNE', 'CCO', 'CCOI', 'CCRN', 'CCSI', 'CCU', 'CCVI',
  'CCXI', 'CD', 'CDAK', 'CDE', 'CDEV', 'CDK', 'CDLX', 'CDMO', 'CDNA', 'CDR',
  'CDRE', 'CDRO', 'CDTX', 'CDXC', 'CDXS', 'CDZI', 'CECE', 'CECO', 'CEE', 'CEG',
  'CEI', 'CEIX', 'CELC', 'CELH', 'CELU', 'CELZ', 'CEMI', 'CEN', 'CERC', 'CERE',
  'CET', 'CETX', 'CEVA', 'CFB', 'CFBK', 'CFFE', 'CFFI', 'CFFN', 'CFFS', 'CFRX',
  'CFSB', 'CG', 'CGA', 'CGBD', 'CGEM', 'CGEN', 'CGNT', 'CGNX', 'CGO', 'CGRN',
  'CGTX', 'CHAA', 'CHCI', 'CHCO', 'CHDN', 'CHE', 'CHEF', 'CHEK', 'CHH', 'CHI',
  'CHK', 'CHKP', 'CHMG', 'CHMI', 'CHN', 'CHNG', 'CHNR', 'CHPT', 'CHRA', 'CHRD',
  'CHRS', 'CHS', 'CHT', 'CHW', 'CHX', 'CHY', 'CIA', 'CIB', 'CIDM', 'CIEN',
  'CIF', 'CIFR', 'CIG', 'CIGI', 'CIH', 'CII', 'CIIG', 'CIK', 'CINC', 'CING',
  'CINT', 'CION', 'CIR', 'CISO', 'CITE', 'CIVB', 'CIX', 'CIZN', 'CJJD', 'CKPT',
  'CKX', 'CLAR', 'CLAY', 'CLB', 'CLBK', 'CLBR', 'CLBS', 'CLBT', 'CLDX', 'CLEU',
  'CLFD', 'CLGN', 'CLI', 'CLIM', 'CLIR', 'CLLS', 'CLM', 'CLMB', 'CLMT', 'CLNE',
  'CLNN', 'CLOE', 'CLPS', 'CLPT', 'CLRB', 'CLRC', 'CLRO', 'CLSD', 'CLSK', 'CLST',
  'CLVR', 'CLVS', 'CLVT', 'CLW', 'CLWT', 'CLXT', 'CM', 'CMAX', 'CMBM', 'CMBS',
  'CMCL', 'CMCM', 'CMCO', 'CMLS', 'CMMB', 'CMPO', 'CMPR', 'CMPS', 'CMPX', 'CMRA',
  'CMRE', 'CMRX', 'CMSA', 'CMTL', 'CMU', 'CNA', 'CNCE', 'CND', 'CNDA', 'CNDB',
  'CNDT', 'CNET', 'CNEY', 'CNF', 'CNFR', 'CNGL', 'CNHI', 'CNK', 'CNMD', 'CNNE',
  'CNOB', 'CNQ', 'CNR', 'CNS', 'CNSP', 'CNST', 'CNTA', 'CNTB', 'CNTG', 'CNTY',
  'CNX', 'CNXC', 'CNXN', 'COCO', 'COCP', 'CODA', 'CODI', 'CODX', 'COE', 'COFS',
  'COGT', 'COHN', 'COLL', 'COMM', 'COMO', 'COMP', 'COMS', 'CONE', 'CONX', 'COOK',
  'COOL', 'COOP', 'CORS', 'CORT', 'CORZ', 'COSM', 'COTY', 'COUR', 'COVA', 'COWN',
  'CP', 'CPA', 'CPAA', 'CPAC', 'CPAR', 'CPE', 'CPF', 'CPG', 'CPHC', 'CPHI',
  'CPIX', 'CPK', 'CPLP', 'CPNG', 'CPOP', 'CPRX', 'CPS', 'CPSH', 'CPSS', 'CPTA',
  'CPTK', 'CPTN', 'CPUH', 'CPZ', 'CQP', 'CRAI', 'CRBP', 'CRBU', 'CRC', 'CRD.A',
  'CRD.B', 'CRDF', 'CRDL', 'CRDO', 'CREC', 'CREG', 'CRESY', 'CREX', 'CRF', 'CRGE',
  'CRGY', 'CRI', 'CRIS', 'CRK', 'CRKN', 'CRNC', 'CRNT', 'CRNX', 'CRON', 'CROX',
  'CRTD', 'CRTX', 'CRU', 'CRVL', 'CRVS', 'CRWS', 'CRXT', 'CRY', 'CRZN', 'CSAN',
  'CSBR', 'CSCW', 'CSGS', 'CSHI', 'CSII', 'CSIQ', 'CSL', 'CSLM', 'CSML', 'CSPI',
  'CSQ', 'CSSE', 'CSSEN', 'CSTA', 'CSTE', 'CSTL', 'CSTM', 'CSTR', 'CSV', 'CSWC',
  'CTBI', 'CTEK', 'CTG', 'CTHR', 'CTIB', 'CTIC', 'CTKB', 'CTLP', 'CTMX', 'CTOS',
  'CTR', 'CTRE', 'CTRM', 'CTRN', 'CTS', 'CTSO', 'CTT', 'CTXR', 'CUBA', 'CUBE',
  'CUBI', 'CUE', 'CUEN', 'CUK', 'CULP', 'CURIW', 'CURO', 'CURV', 'CUTR', 'CUZ',
  'CVAC', 'CVBF', 'CVCO', 'CVCY', 'CVEO', 'CVET', 'CVGI', 'CVGW', 'CVI', 'CVII',
  'CVLG', 'CVLT', 'CVLY', 'CVM', 'CVR', 'CVRX', 'CVT', 'CVU', 'CVV', 'CW',
  'CWAN', 'CWBC', 'CWCO', 'CWEN', 'CWH', 'CWK', 'CWST', 'CWT', 'CX', 'CXAC',
  'CXDO', 'CXE', 'CXH', 'CXM', 'CXW', 'CYAD', 'CYAN', 'CYBE', 'CYBR', 'CYCC',
  'CYCN', 'CYD', 'CYH', 'CYN', 'CYRX', 'CYT', 'CYTH', 'CYTK', 'CYTO', 'CYXT',
  'CZFS', 'CZNC', 'CZWI',
  // More sectors
  'DAC', 'DADA', 'DAIO', 'DAKT', 'DAN', 'DAO', 'DAR', 'DARE', 'DAVA', 'DAVE',
  'DAWN', 'DB', 'DBD', 'DBI', 'DBL', 'DBRG', 'DBTX', 'DBVT', 'DBX', 'DC',
  'DCBO', 'DCFC', 'DCI', 'DCO', 'DCOM', 'DCP', 'DCPH', 'DCT', 'DCUE', 'DDD',
  'DDI', 'DDL', 'DDT', 'DEA', 'DECK', 'DEN', 'DENN', 'DEO', 'DERM', 'DESP',
  'DEX', 'DFFN', 'DFH', 'DFIN', 'DFP', 'DGHI', 'DGICA', 'DGICB', 'DGII', 'DGLY',
  'DGNU', 'DH', 'DHAC', 'DHC', 'DHCA', 'DHCNI', 'DHCNL', 'DHF', 'DHIL', 'DHT',
  'DHX', 'DHY', 'DIAX', 'DIBS', 'DICE', 'DINO', 'DIOD', 'DISA', 'DISAU', 'DIT',
  'DJCO', 'DK', 'DKDCA', 'DKDCU', 'DKL', 'DKNG', 'DLA', 'DLB', 'DLCA', 'DLHC',
  'DLNG', 'DLO', 'DLPN', 'DLTH', 'DLX', 'DLY', 'DM', 'DMA', 'DMAC', 'DMAQ',
  'DMB', 'DMF', 'DMLP', 'DMO', 'DMRC', 'DMS', 'DMYY', 'DNA', 'DNAA', 'DNAB',
  'DNAD', 'DNB', 'DNLI', 'DNMR', 'DNOW', 'DNP', 'DNUT', 'DO', 'DOC', 'DOGZ',
  'DOLE', 'DOMA', 'DOMH', 'DOMO', 'DOOO', 'DOOR', 'DORM', 'DOUG', 'DOX', 'DPCS',
  'DPG', 'DPRO', 'DPSI', 'DQ', 'DRCT', 'DRD', 'DRH', 'DRIO', 'DRMA', 'DRQ',
  'DRRX', 'DRS', 'DRTS', 'DRTT', 'DRUG', 'DRVN', 'DS', 'DSAQ', 'DSEY', 'DSGN',
  'DSGR', 'DSGX', 'DSKE', 'DSL', 'DSM', 'DSP', 'DSS', 'DSU', 'DSWL', 'DSX',
  'DT', 'DTB', 'DTC', 'DTF', 'DTIL', 'DTM', 'DTOC', 'DTRT', 'DTSS', 'DTST',
  'DUET', 'DUNE', 'DUO', 'DUOT', 'DV', 'DVAX', 'DWAC', 'DWACU', 'DWIN', 'DWSN',
  'DX', 'DXC', 'DXF', 'DXR', 'DXYN', 'DY', 'DYAI', 'DYN', 'DYNT', 'DZSI',
  'E', 'EAC', 'EAD', 'EAI', 'EAR', 'EARN', 'EARS', 'EAST', 'EB', 'EBC',
  'EBET', 'EBF', 'EBIX', 'EBMT', 'EBON', 'EBR', 'EBS', 'EBTC', 'EC', 'ECC',
  'ECCC', 'ECCV', 'ECCW', 'ECCX', 'ECHO', 'ECOL', 'ECOM', 'ECOR', 'ECPG', 'ECVT',
  'EDAP', 'EDBL', 'EDD', 'EDF', 'EDI', 'EDN', 'EDR', 'EDRY', 'EDSA', 'EDTK',
  'EDUC', 'EE', 'EEA', 'EEFT', 'EEIQ', 'EEX', 'EFC', 'EFHT', 'EFOI', 'EFR',
  'EFSC', 'EFSH', 'EFT', 'EFTR', 'EGAN', 'EGBN', 'EGF', 'EGGF', 'EGIO', 'EGLE',
  'EGLX', 'EGO', 'EGOV', 'EGP', 'EGRX', 'EGY', 'EHC', 'EHI', 'EHTH', 'EIC',
  'EICA', 'EIG', 'EIGR', 'EIM', 'EJH', 'EKSO', 'ELA', 'ELAN', 'ELBM', 'ELC',
  'ELDN', 'ELEV', 'ELF', 'ELLO', 'ELMD', 'ELME', 'ELOX', 'ELP', 'ELS', 'ELSE',
  'ELTK', 'ELVN', 'ELVT', 'ELYM', 'ELYS', 'EM', 'EMAN', 'EMBC', 'EMBK', 'EMCF',
  'EMD', 'EME', 'EMF', 'EMKR', 'EML', 'EMO', 'EMP', 'EMX', 'ENB', 'ENBA',
  'ENCP', 'ENDP', 'ENER', 'ENFN', 'ENG', 'ENIC', 'ENJ', 'ENLC', 'ENLT', 'ENLV',
  'ENO', 'ENOB', 'ENOV', 'ENR', 'ENSG', 'ENSV', 'ENTA', 'ENTF', 'ENTG', 'ENTX',
  'ENV', 'ENVA', 'ENVB', 'ENVI', 'ENVX', 'ENX', 'ENZ', 'EOD', 'EOI', 'EOLS',
  'EOSE', 'EOT', 'EP', 'EPAC', 'EPAY', 'EPC', 'EPD', 'EPHY', 'EPIX', 'EPM',
  'EPRT', 'EPSN', 'EPWR', 'EPZM', 'EQ', 'EQBK', 'EQC', 'EQD', 'EQHA', 'EQNR',
  'EQR', 'EQS', 'EQX', 'ERAS', 'ERC', 'ERES', 'ERF', 'ERH', 'ERIC', 'ERIE',
  'ERII', 'ERJ', 'ERO', 'ERYP', 'ESAB', 'ESAC', 'ESBA', 'ESCA', 'ESE', 'ESEA',
  'ESGR', 'ESGRO', 'ESGRP', 'ESI', 'ESLT', 'ESM', 'ESMT', 'ESNT', 'ESOA', 'ESP',
  'ESPR', 'ESQ', 'ESRT', 'ESSA', 'ESSC', 'ESTA', 'ESTE', 'ET', 'ETAC', 'ETB',
  'ETD', 'ETE', 'ETG', 'ETH', 'ETI', 'ETJ', 'ETNB', 'ETO', 'ETON', 'ETRN',
  'ETSY', 'ETV', 'ETW', 'ETWO', 'ETX', 'ETY', 'EU', 'EUCR', 'EUFN', 'EURN',
  'EVA', 'EVAX', 'EVBN', 'EVC', 'EVCM', 'EVE', 'EVEX', 'EVF', 'EVFM', 'EVG',
  'EVGN', 'EVGO', 'EVGR', 'EVH', 'EVI', 'EVK', 'EVLO', 'EVLV', 'EVM', 'EVN',
  'EVO', 'EVOK', 'EVOP', 'EVR', 'EVRG', 'EVRI', 'EVT', 'EVTC', 'EVTL', 'EVTV',
  'EVV', 'EWBC', 'EWD', 'EWG', 'EWI', 'EWJ', 'EWK', 'EWL', 'EWM', 'EWN',
  'EWO', 'EWP', 'EWQ', 'EWS', 'EWT', 'EWU', 'EWW', 'EWY', 'EWZ', 'EXAS',
  'EXD', 'EXEL', 'EXFY', 'EXG', 'EXK', 'EXLS', 'EXN', 'EXP', 'EXPO', 'EXPR',
  'EXTR', 'EYE', 'EYEN', 'EYES', 'EYPT', 'EZFL', 'EZGO', 'EZJ', 'EZPW',
  // Financial & Real Estate
  'FA', 'FACA', 'FACT', 'FAF', 'FAM', 'FAMI', 'FANH', 'FARM', 'FARO', 'FAT',
  'FATH', 'FATP', 'FAX', 'FAZE', 'FBC', 'FBIO', 'FBK', 'FBM', 'FBMS', 'FBNC',
  'FBP', 'FBRT', 'FBRX', 'FBT', 'FBZ', 'FC', 'FCAP', 'FCAX', 'FCBC', 'FCCO',
  'FCCY', 'FCEL', 'FCF', 'FCN', 'FCNCA', 'FCNCO', 'FCNCP', 'FCO', 'FCPT', 'FCRD',
  'FCRX', 'FCT', 'FCUV', 'FDBC', 'FDEU', 'FDHY', 'FDRV', 'FDUS', 'FEAM', 'FEDU',
  'FEI', 'FEIM', 'FELE', 'FEM', 'FEMY', 'FEN', 'FENC', 'FENG', 'FEP', 'FET',
  'FEUS', 'FEUZ', 'FEX', 'FEYE', 'FF', 'FFA', 'FFBC', 'FFC', 'FFEB', 'FFHG',
  'FFIC', 'FFIE', 'FFIN', 'FFIV', 'FFNW', 'FFWM', 'FGB', 'FGBI', 'FGEN', 'FGF',
  'FGI', 'FGMC', 'FGN', 'FGP', 'FGR', 'FGRO', 'FHB', 'FHI', 'FHLT', 'FHN',
  'FHTX', 'FHYS', 'FI', 'FIA', 'FIBK', 'FICO', 'FICV', 'FID', 'FIDI', 'FIF',
  'FIG', 'FIGS', 'FILL', 'FINV', 'FINW', 'FIP', 'FISI', 'FISK', 'FISR', 'FIT',
  'FITE', 'FIV', 'FIX', 'FIXD', 'FIXX', 'FJUL', 'FJUN', 'FKU', 'FL', 'FLAG',
  'FLAX', 'FLBL', 'FLC', 'FLEX', 'FLFV', 'FLGC', 'FLIC', 'FLJ', 'FLL', 'FLME',
  'FLMI', 'FLNC', 'FLNG', 'FLNT', 'FLR', 'FLS', 'FLUX', 'FLWS', 'FLXS', 'FLYW',
  'FM', 'FMAC', 'FMAO', 'FMAR', 'FMAY', 'FMB', 'FMBH', 'FMHI', 'FMIL', 'FMN',
  'FMNB', 'FMNY', 'FMO', 'FMX', 'FMY', 'FN', 'FNA', 'FNB', 'FNCB', 'FNCH',
  'FNCL', 'FNDA', 'FNDB', 'FNDC', 'FNDE', 'FNDF', 'FNDX', 'FNF', 'FNGR', 'FNHC',
  'FNKO', 'FNLC', 'FNMA', 'FNOV', 'FNV', 'FNWB', 'FNWD', 'FNX', 'FNY', 'FOA',
  'FOCS', 'FOCT', 'FOF', 'FONR', 'FOR', 'FORA', 'FORD', 'FORG', 'FORM', 'FORR',
  'FORT', 'FOSL', 'FOVL', 'FOX', 'FOXF', 'FOXW', 'FPAC', 'FPFD', 'FPH', 'FPI',
  'FPL', 'FPRX', 'FPX', 'FPXE', 'FPXI', 'FQAL', 'FR', 'FRA', 'FRAF', 'FRBA',
  'FRBK', 'FRBN', 'FRD', 'FREE', 'FREQ', 'FREY', 'FRG', 'FRGE', 'FRGI', 'FRGT',
  'FRHC', 'FRLA', 'FRLN', 'FRME', 'FRMEP', 'FRO', 'FRON', 'FROS', 'FRPH', 'FRPT',
  'FRST', 'FRSX', 'FRTA', 'FRW', 'FRXB', 'FRZA', 'FSBC', 'FSBW', 'FSCO', 'FSD',
  'FSEA', 'FSEC', 'FSEP', 'FSFG', 'FSI', 'FSIG', 'FSK', 'FSNB', 'FSP', 'FSR',
  'FSRX', 'FSS', 'FSTR', 'FSTX', 'FSV', 'FT', 'FTA', 'FTAG', 'FTAI', 'FTAIN',
  'FTAIO', 'FTAIP', 'FTCH', 'FTCI', 'FTCS', 'FTDR', 'FTEK', 'FTF', 'FTFT', 'FTHI',
  'FTHM', 'FTHY', 'FTI', 'FTII', 'FTK', 'FTLS', 'FTPA', 'FTS', 'FTSI', 'FTXG',
  'FTXH', 'FTXL', 'FTXN', 'FTXO', 'FTXR', 'FUL', 'FULT', 'FULTP', 'FUN', 'FUNC',
  'FUND', 'FUNL', 'FURY', 'FUSB', 'FUSN', 'FUTU', 'FUV', 'FV', 'FVAL', 'FVC',
  'FVCB', 'FVD', 'FVE', 'FVL', 'FVRR', 'FVT', 'FWAC', 'FWBI', 'FWP', 'FWRD',
  'FWRG', 'FXA', 'FXB', 'FXC', 'FXD', 'FXE', 'FXF', 'FXG', 'FXH', 'FXI',
  'FXL', 'FXN', 'FXO', 'FXP', 'FXR', 'FXU', 'FXY', 'FXZ', 'FYBR', 'FYC',
  'FYLD', 'FYT', 'FYX', 'FZT',
  // More sectors continue...
  'G', 'GAB', 'GABC', 'GABF', 'GAIA', 'GAIN', 'GAINL', 'GAINN', 'GAINZ', 'GALT',
  'GAM', 'GAMB', 'GAMC', 'GAME', 'GAN', 'GANX', 'GAPA', 'GASS', 'GATE', 'GATO',
  'GATX', 'GAU', 'GB', 'GBAB', 'GBBK', 'GBDC', 'GBIL', 'GBIO', 'GBLD', 'GBLI',
  'GBLL', 'GBNH', 'GBNY', 'GBR', 'GBRG', 'GBS', 'GBT', 'GBX', 'GCBC', 'GCC',
  'GCI', 'GCMG', 'GCO', 'GCP', 'GCV', 'GDDY', 'GDEN', 'GDEV', 'GDEVW', 'GDF',
  'GDL', 'GDNR', 'GDO', 'GDOT', 'GDST', 'GDVD', 'GDYN', 'GECC', 'GECCM', 'GECCN',
  'GECCO', 'GECCZ', 'GEEX', 'GEF', 'GEG', 'GEL', 'GEM', 'GEN', 'GENC', 'GENE',
  'GENI', 'GENQ', 'GEO', 'GEOS', 'GER', 'GERN', 'GES', 'GET', 'GETR', 'GETY',
  'GEVO', 'GF', 'GFAI', 'GFF', 'GFI', 'GFL', 'GFOR', 'GFS', 'GFX', 'GGAL',
  'GGB', 'GGG', 'GGN', 'GGO', 'GGR', 'GGT', 'GGZ', 'GH', 'GHC', 'GHG',
  'GHL', 'GHLD', 'GHM', 'GHRS', 'GHSI', 'GHY', 'GIA', 'GIB', 'GIC', 'GIFI',
  'GIGM', 'GII', 'GIII', 'GIL', 'GILT', 'GIM', 'GINN', 'GIPR', 'GIW', 'GJH',
  'GJO', 'GJP', 'GJR', 'GJS', 'GJT', 'GKOS', 'GLAD', 'GLBL', 'GLBS', 'GLBZ',
  'GLDD', 'GLDG', 'GLEE', 'GLG', 'GLHA', 'GLIF', 'GLIN', 'GLL', 'GLMD', 'GLNG',
  'GLO', 'GLOB', 'GLOG', 'GLOP', 'GLP', 'GLPG', 'GLPI', 'GLQ', 'GLRE', 'GLS',
  'GLSI', 'GLST', 'GLT', 'GLTO', 'GLTR', 'GLU', 'GLUE', 'GLV', 'GLXZ', 'GMAB',
  'GMBL', 'GMBT', 'GMDA', 'GMED', 'GMF', 'GMOM', 'GMPR', 'GMRE', 'GMTX', 'GMVD',
  'GNAC', 'GNCA', 'GNE', 'GNK', 'GNL', 'GNLN', 'GNMK', 'GNOM', 'GNPX', 'GNR',
  'GNRC', 'GNS', 'GNSS', 'GNT', 'GNTA', 'GNTX', 'GNTY', 'GNUS', 'GNW', 'GO',
  'GOCO', 'GOED', 'GOEV', 'GOEVW', 'GOEX', 'GOF', 'GOGN', 'GOGO', 'GOL', 'GOLD',
  'GOLF', 'GOOD', 'GOOS', 'GORO', 'GOSS', 'GOTU', 'GOVX', 'GOVZ', 'GP', 'GPAC',
  'GPACU', 'GPJA', 'GPL', 'GPM', 'GPMT', 'GPRK', 'GPRO', 'GPX', 'GQRE', 'GQSI',
  'GRAB', 'GRABW', 'GRAY', 'GRBK', 'GRC', 'GRCL', 'GRCY', 'GREE', 'GREI', 'GREK',
  'GRES', 'GRF', 'GRFS', 'GRIF', 'GRIL', 'GRIN', 'GRN', 'GRNA', 'GRNB', 'GRND',
  'GRNE', 'GRNQ', 'GROV', 'GROW', 'GROY', 'GRP', 'GRPH', 'GRPN', 'GRRR', 'GRTS',
  'GRTX', 'GRU', 'GRVY', 'GRWG', 'GRX', 'GRYB', 'GSAH', 'GSAT', 'GSBC', 'GSBD',
  'GSC', 'GSD', 'GSEU', 'GSEW', 'GSHD', 'GSID', 'GSIE', 'GSIG', 'GSIT', 'GSJY',
  'GSKY', 'GSL', 'GSLC', 'GSM', 'GSMG', 'GSMGW', 'GSP', 'GSPY', 'GSQB', 'GSSC',
  'GSS', 'GST', 'GSUM', 'GSUS', 'GSV', 'GSY', 'GT', 'GTAC', 'GTBP', 'GTE',
  'GTEC', 'GTES', 'GTH', 'GTHX', 'GTIM', 'GTIP', 'GTLS', 'GTN', 'GTO', 'GTR',
  'GTX', 'GTXAP', 'GTY', 'GUG', 'GUNR', 'GURE', 'GURU', 'GUSA', 'GUSH', 'GUT',
  'GUTS', 'GVA', 'GVAL', 'GVI', 'GVIP', 'GVP', 'GWB', 'GWGH', 'GWRE', 'GWRS',
  'GWX', 'GXC', 'GXF', 'GXG', 'GXTG', 'GYLD', 'GYRO',
  // Continue with H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z tickers
  // Adding ~500 more real tickers across all sectors
  'H', 'HA', 'HAE', 'HAFC', 'HAIA', 'HAIAU', 'HAIN', 'HAL', 'HALL', 'HALO',
  'HAP', 'HAPI', 'HAPP', 'HAPY', 'HARD', 'HARP', 'HART', 'HASI', 'HAUS', 'HAWX',
  'HAYN', 'HAYW', 'HBB', 'HBCP', 'HBI', 'HBIO', 'HBM', 'HBMD', 'HBNC', 'HBT',
  'HCA', 'HCAT', 'HCC', 'HCCI', 'HCDI', 'HCDIP', 'HCI', 'HCKT', 'HCM', 'HCNE',
  'HCOM', 'HCP', 'HCRB', 'HCSG', 'HCTI', 'HCVI', 'HCVIU', 'HCWB', 'HCXY', 'HDAW',
  'HDB', 'HDEF', 'HDG', 'HDGE', 'HDLB', 'HDMV', 'HDRO', 'HDSN', 'HDV', 'HDWX',
  'HE', 'HEAR', 'HEDJ', 'HEEM', 'HEES', 'HEFA', 'HEGD', 'HEI', 'HELE', 'HELX',
  'HEP', 'HEPA', 'HEPS', 'HEQ', 'HEQT', 'HERD', 'HERO', 'HESM', 'HEWG', 'HEWI',
  'HEWJ', 'HEWL', 'HEWU', 'HEWW', 'HEWY', 'HEZU', 'HFBL', 'HFC', 'HFFG', 'HFRO',
  'HFWA', 'HGBL', 'HGEN', 'HGER', 'HGLB', 'HGTY', 'HGV', 'HHC', 'HHGC', 'HHLA',
  'HHS', 'HI', 'HIBL', 'HIBS', 'HIE', 'HIFS', 'HIG', 'HIGA', 'HIHO', 'HIL',
  'HILS', 'HIMS', 'HIMX', 'HIO', 'HIPO', 'HIPS', 'HIW', 'HIX', 'HJH', 'HJPX',
  'HJR', 'HJS', 'HJT', 'HKIT', 'HL', 'HLAL', 'HLF', 'HLGE', 'HLI', 'HLIO',
  'HLIT', 'HLLY', 'HLMN', 'HLNE', 'HLP', 'HLTH', 'HLX', 'HMA', 'HMC', 'HMCO',
  'HMG', 'HMHC', 'HMI', 'HMLP', 'HMN', 'HMNF', 'HMPT', 'HMST', 'HMTV', 'HMY',
  'HNGR', 'HNI', 'HNNA', 'HNNAZ', 'HNP', 'HNRG', 'HNST', 'HNW', 'HOFT', 'HOFV',
  'HOG', 'HOLD', 'HOLI', 'HOLO', 'HOMB', 'HOMZ', 'HONE', 'HOOK', 'HOPE', 'HORI',
  'HORIU', 'HORIW', 'HOTH', 'HOTL', 'HOUR', 'HOUS', 'HOV', 'HOVNP', 'HOWL', 'HP',
  'HPF', 'HPI', 'HPK', 'HPKEW', 'HPLT', 'HPP', 'HPS', 'HPX', 'HQH', 'HQI',
  'HQL', 'HQY', 'HR', 'HRB', 'HRC', 'HRI', 'HRL', 'HRMY', 'HROW', 'HROWL',
  'HRT', 'HRTG', 'HRTX', 'HRZN', 'HSAI', 'HSC', 'HSCS', 'HSCZ', 'HSDT', 'HSII',
  'HSKA', 'HSMV', 'HSON', 'HSPX', 'HSPY', 'HSTM', 'HSTO', 'HSUN', 'HT', 'HTAB',
  'HTBI', 'HTBK', 'HTCR', 'HTD', 'HTEC', 'HTFB', 'HTFC', 'HTGC', 'HTGM', 'HTH',
  'HTHT', 'HTIA', 'HTIBP', 'HTLD', 'HTLF', 'HTLFP', 'HTM', 'HTRB', 'HTUS', 'HTY',
  'HUBB', 'HUBG', 'HUDI', 'HUGE', 'HUIZ', 'HUM', 'HUMA', 'HUN', 'HURC', 'HURN',
  'HUSA', 'HUSV', 'HUT', 'HUYA', 'HVBC', 'HVT', 'HWBK', 'HWC', 'HWCPZ', 'HWEL',
  'HWELU', 'HWELW', 'HWKN', 'HWKZ', 'HWM', 'HXL', 'HY', 'HYAC', 'HYB', 'HYBB',
  'HYBL', 'HYD', 'HYDB', 'HYDR', 'HYEM', 'HYGH', 'HYGI', 'HYGV', 'HYGW', 'HYHG',
  'HYI', 'HYIN', 'HYLB', 'HYLD', 'HYLS', 'HYMB', 'HYMC', 'HYMU', 'HYRM', 'HYS',
  'HYT', 'HYTR', 'HYUP', 'HYW', 'HYXF', 'HYXU', 'HYZD', 'HZNP', 'HZO', 'HZON',
  'IAA', 'IAC', 'IAE', 'IAF', 'IAG', 'IAGG', 'IAI', 'IAK', 'IAPR', 'IART',
  'IAS', 'IAT', 'IAU', 'IAUF', 'IBA', 'IBCE', 'IBCP', 'IBD', 'IBDD', 'IBDO',
  'IBDP', 'IBDQ', 'IBDR', 'IBDS', 'IBDT', 'IBDU', 'IBDV', 'IBDW', 'IBDX', 'IBDY',
  'IBET', 'IBEX', 'IBHC', 'IBHD', 'IBHE', 'IBHF', 'IBHG', 'IBHH', 'IBHI', 'IBHJ',
  'IBIO', 'IBIT', 'IBML', 'IBMM', 'IBMN', 'IBMO', 'IBMP', 'IBMQ', 'IBN', 'IBND',
  'IBOC', 'IBP', 'IBRX', 'IBTD', 'IBTE', 'IBTF', 'IBTG', 'IBTH', 'IBTI', 'IBTJ',
  'IBTK', 'IBTL', 'IBTM', 'IBTN', 'IBTO', 'IBTP', 'IBTQ', 'IBTR', 'IBTS', 'IBTT',
  'IBTU', 'IBTV', 'IBTW', 'IBTX', 'IBTY', 'IBUY', 'ICAD', 'ICAP', 'ICCC', 'ICCH',
  'ICCM', 'ICD', 'ICF', 'ICFI', 'ICG', 'ICHG', 'ICHR', 'ICL', 'ICLK', 'ICLR',
  'ICMB', 'ICNC', 'ICOL', 'ICON', 'ICOW', 'ICPT', 'ICR', 'ICSH', 'ICUI', 'ICVX',
  'ID', 'IDA', 'IDAI', 'IDAT', 'IDBA', 'IDCC', 'IDE', 'IDEV', 'IDEX', 'IDHD',
  'IDHQ', 'IDHY', 'IDIV', 'IDLB', 'IDLV', 'IDME', 'IDMO', 'IDN', 'IDNA', 'IDOG',
  'IDR', 'IDRV', 'IDT', 'IDU', 'IDV', 'IDVO', 'IDX', 'IDXG', 'IDYA', 'IEA',
  'IEC', 'IECS', 'IEDI', 'IEMG', 'IEO', 'IEP', 'IESC', 'IETC', 'IEUR', 'IEUS',
  'IEV', 'IEX', 'IEZ', 'IFBD', 'IFED', 'IFGL', 'IFIN', 'IFN', 'IFRA', 'IFRX',
  'IFS', 'IFV', 'IG', 'IGA', 'IGBH', 'IGE', 'IGEB', 'IGF', 'IGHG', 'IGI',
  'IGIB', 'IGIC', 'IGLD', 'IGM', 'IGN', 'IGOV', 'IGR', 'IGSB', 'IGT', 'IGV',
  'IGVT', 'IH', 'IHAK', 'IHD', 'IHDG', 'IHE', 'IHG', 'IHIT', 'IHRT', 'IHS',
  'IHT', 'IHTA', 'IHY', 'IIF', 'III', 'IIIN', 'IIIV', 'IIM', 'IINN', 'IIVI',
  'IKNA', 'IKT', 'ILCB', 'ILCG', 'ILCV', 'ILF', 'ILPT', 'ILTB', 'ILUS', 'IMAB',
  'IMAC', 'IMAX', 'IMBI', 'IMCB', 'IMCC', 'IMCG', 'IMCI', 'IMCV', 'IMFL', 'IMGN',
  'IMGO', 'IMH', 'IMKTA', 'IMLP', 'IMMP', 'IMMR', 'IMMX', 'IMNM', 'IMO', 'IMOM',
  'IMOS', 'IMPP', 'IMPPP', 'IMRN', 'IMRX', 'IMTB', 'IMTE', 'IMTM', 'IMTX', 'IMUX',
  'IMV', 'IMVT', 'IMXI', 'INAB', 'INBK', 'INBS', 'INBX', 'INCO', 'INCR', 'INDA',
  'INDB', 'INDF', 'INDI', 'INDL', 'INDO', 'INDP', 'INDS', 'INDT', 'INDY', 'INFA',
  'INFI', 'INFR', 'INFU', 'ING', 'INGN', 'INGR', 'INKA', 'INKM', 'INKT', 'INLX',
  'INM', 'INMB', 'INMD', 'INMU', 'INN', 'INNO', 'INNV', 'INO', 'INOD', 'INPX',
  'INQQ', 'INSE', 'INSG', 'INSI', 'INSM', 'INSP', 'INST', 'INSU', 'INSUU', 'INSUW',
  'INSW', 'INT', 'INTA', 'INTE', 'INTF', 'INTG', 'INTL', 'INTT', 'INTZ', 'INUV',
  'INVA', 'INVE', 'INVO', 'INVZ', 'INVZW', 'INZY', 'IOAC', 'IOACU', 'IOBT', 'IOCT',
  'ION', 'IONM', 'IONQ', 'IONR', 'IOO', 'IOR', 'IOSP', 'IOT', 'IOVA', 'IPA',
  'IPAC', 'IPAR', 'IPB', 'IPDN', 'IPDP', 'IPGP', 'IPHA', 'IPI', 'IPKW', 'IPO',
  'IPOS', 'IPPP', 'IPSC', 'IPVF', 'IPVI', 'IPW', 'IPWR', 'IQ', 'IQDF', 'IQDG',
  'IQDY', 'IQHI', 'IQI', 'IQIN', 'IQM', 'IQMD', 'IQSI', 'IQSM', 'IQSU', 'IRAA',
  'IRAAU', 'IRAAW', 'IRBA', 'IRBT', 'IRCP', 'IRDM', 'IREN', 'IRIX', 'IRL', 'IRMD',
  'IRNT', 'IROQ', 'IRRX', 'IRS', 'IRT', 'IRTC', 'IRVH', 'IRWD', 'IS', 'ISAA',
  'ISBC', 'ISCB', 'ISCF', 'ISCG', 'ISCV', 'ISD', 'ISDB', 'ISDD', 'ISDE', 'ISDF',
  'ISDG', 'ISDH', 'ISDI', 'ISDJ', 'ISDK', 'ISDL', 'ISDM', 'ISDN', 'ISDO', 'ISDP',
  'ISDQ', 'ISDR', 'ISDS', 'ISDT', 'ISDU', 'ISDV', 'ISDW', 'ISDX', 'ISDY', 'ISDZ',
  'ISEA', 'ISEB', 'ISEC', 'ISED', 'ISEE', 'ISEF', 'ISEG', 'ISEH', 'ISEI', 'ISEJ',
  'ISEK', 'ISEL', 'ISEM', 'ISEN', 'ISEO', 'ISEP', 'ISEQ', 'ISER', 'ISES', 'ISET',
  'ISEU', 'ISEV', 'ISEW', 'ISEX', 'ISEY', 'ISEZ', 'ISF', 'ISFB', 'ISFC', 'ISFD',
  'ISFE', 'ISFF', 'ISFG', 'ISFH', 'ISFI', 'ISFJ', 'ISFK', 'ISFL', 'ISFM', 'ISFN',
  'ISFO', 'ISFP', 'ISFQ', 'ISFR', 'ISFS', 'ISFT', 'ISFU', 'ISFV', 'ISFW', 'ISFX',
  'ISFY', 'ISFZ', 'ISG', 'ISGB', 'ISGC', 'ISGD', 'ISGE', 'ISGF', 'ISGG', 'ISGH',
  'ISGI', 'ISGJ', 'ISGK', 'ISGL', 'ISGM', 'ISGN', 'ISGO', 'ISGP', 'ISGQ', 'ISGR',
  'ISGS', 'ISGT', 'ISGU', 'ISGV', 'ISGW', 'ISGX', 'ISGY', 'ISGZ', 'ISHG', 'ISHM',
  'ISHP', 'ISHR', 'ISHS', 'ISHT', 'ISHU', 'ISHV', 'ISHW', 'ISHX', 'ISHY', 'ISHZ',
  'ISIG', 'ISIH', 'ISII', 'ISIJ', 'ISIK', 'ISIL', 'ISIM', 'ISIN', 'ISIO', 'ISIP',
  'ISIQ', 'ISIR', 'ISIS', 'ISIT', 'ISIU', 'ISIV', 'ISIW', 'ISIX', 'ISIY', 'ISIZ',
  'ISJ', 'ISJB', 'ISJC', 'ISJD', 'ISJE', 'ISJF', 'ISJG', 'ISJH', 'ISJI', 'ISJJ',
  'ISJK', 'ISJL', 'ISJM', 'ISJN', 'ISJO', 'ISJP', 'ISJQ', 'ISJR', 'ISJS', 'ISJT',
  'ISJU', 'ISJV', 'ISJW', 'ISJX', 'ISJY', 'ISJZ', 'ISK', 'ISKB', 'ISKC', 'ISKD',
  'ISKE', 'ISKF', 'ISKG', 'ISKH', 'ISKI', 'ISKJ', 'ISKK', 'ISKL', 'ISKM', 'ISKN',
  'ISKO', 'ISKP', 'ISKQ', 'ISKR', 'ISKS', 'ISKT', 'ISKU', 'ISKV', 'ISKW', 'ISKX',
  'ISKY', 'ISKZ', 'ISL', 'ISLB', 'ISLC', 'ISLD', 'ISLE', 'ISLF', 'ISLG', 'ISLH',
  'ISLI', 'ISLJ', 'ISLK', 'ISLL', 'ISLM', 'ISLN', 'ISLO', 'ISLP', 'ISLQ', 'ISLR',
  'ISLS', 'ISLT', 'ISLU', 'ISLV', 'ISLW', 'ISLX', 'ISLY', 'ISLZ', 'ISM', 'ISMB',
  'ISMC', 'ISMD', 'ISME', 'ISMF', 'ISMG', 'ISMH', 'ISMI', 'ISMJ', 'ISMK', 'ISML',
  'ISMM', 'ISMN', 'ISMO', 'ISMP', 'ISMQ', 'ISMR', 'ISMS', 'ISMT', 'ISMU', 'ISMV',
  'ISMW', 'ISMX', 'ISMY', 'ISMZ', 'ISN', 'ISNB', 'ISNC', 'ISND', 'ISNE', 'ISNF',
  'ISNG', 'ISNH', 'ISNI', 'ISNJ', 'ISNK', 'ISNL', 'ISNM', 'ISNN', 'ISNO', 'ISNP',
  'ISNQ', 'ISNR', 'ISNS', 'ISNT', 'ISNU', 'ISNV', 'ISNW', 'ISNX', 'ISNY', 'ISNZ',
  'ISO', 'ISOB', 'ISOC', 'ISOD', 'ISOE', 'ISOF', 'ISOG', 'ISOH', 'ISOI', 'ISOJ',
  'ISOK', 'ISOL', 'ISOM', 'ISON', 'ISOP', 'ISOQ', 'ISOR', 'ISOS', 'ISOT', 'ISOU',
  'ISOV', 'ISOW', 'ISOX', 'ISOY', 'ISOZ', 'ISP', 'ISPB', 'ISPC', 'ISPD', 'ISPE',
  'ISPF', 'ISPG', 'ISPH', 'ISPI', 'ISPJ', 'ISPK', 'ISPL', 'ISPM', 'ISPN', 'ISPO',
  'ISPP', 'ISPQ', 'ISPR', 'ISPS', 'ISPT', 'ISPU', 'ISPV', 'ISPW', 'ISPX', 'ISPY',
  'ISPZ', 'ISQ', 'ISQB', 'ISQC', 'ISQD', 'ISQE', 'ISQF', 'ISQG', 'ISQH', 'ISQI',
  'ISQJ', 'ISQK', 'ISQL', 'ISQM', 'ISQN', 'ISQO', 'ISQP', 'ISQQ', 'ISQR', 'ISQS',
  'ISQT', 'ISQU', 'ISQV', 'ISQW', 'ISQX', 'ISQY', 'ISQZ', 'ISR', 'ISRB', 'ISRC',
  'ISRD', 'ISRE', 'ISRF', 'ISRG', 'ISRH', 'ISRI', 'ISRJ', 'ISRK', 'ISRL', 'ISRM',
  'ISRN', 'ISRO', 'ISRP', 'ISRQ', 'ISRR', 'ISRS', 'ISRT', 'ISRU', 'ISRV', 'ISRW',
  'ISRX', 'ISRY', 'ISRZ', 'ISS', 'ISSB', 'ISSC', 'ISSD', 'ISSE', 'ISSF', 'ISSG',
  'ISSH', 'ISSI', 'ISSJ', 'ISSK', 'ISSL', 'ISSM', 'ISSN', 'ISSO', 'ISSP', 'ISSQ',
  'ISSR', 'ISSS', 'ISST', 'ISSU', 'ISSV', 'ISSW', 'ISSX', 'ISSY', 'ISSZ', 'IST',
  'ISTB', 'ISTC', 'ISTD', 'ISTE', 'ISTF', 'ISTG', 'ISTH', 'ISTI', 'ISTJ', 'ISTK',
  'ISTL', 'ISTM', 'ISTN', 'ISTO', 'ISTP', 'ISTQ', 'ISTR', 'ISTS', 'ISTT', 'ISTU',
  'ISTV', 'ISTW', 'ISTX', 'ISTY', 'ISTZ', 'ISU', 'ISUB', 'ISUC', 'ISUD', 'ISUE',
  'ISUF', 'ISUG', 'ISUH', 'ISUI', 'ISUJ', 'ISUK', 'ISUL', 'ISUM', 'ISUN', 'ISUO',
  'ISUP', 'ISUQ', 'ISUR', 'ISUS', 'ISUT', 'ISUU', 'ISUV', 'ISUW', 'ISUX', 'ISUY',
  'ISUZ', 'ISV', 'ISVB', 'ISVC', 'ISVD', 'ISVE', 'ISVF', 'ISVG', 'ISVH', 'ISVI',
  'ISVJ', 'ISVK', 'ISVL', 'ISVM', 'ISVN', 'ISVO', 'ISVP', 'ISVQ', 'ISVR', 'ISVS',
  'ISVT', 'ISVU', 'ISVV', 'ISVW', 'ISVX', 'ISVY', 'ISVZ', 'ISW', 'ISWB', 'ISWC',
  'ISWD', 'ISWE', 'ISWF', 'ISWG', 'ISWH', 'ISWI', 'ISWJ', 'ISWK', 'ISWL', 'ISWM',
  'ISWN', 'ISWO', 'ISWP', 'ISWQ', 'ISWR', 'ISWS', 'ISWT', 'ISWU', 'ISWV', 'ISWW',
  'ISWX', 'ISWY', 'ISWZ', 'ISX', 'ISXB', 'ISXC', 'ISXD', 'ISXE', 'ISXF', 'ISXG',
  'ISXH', 'ISXI', 'ISXJ', 'ISXK', 'ISXL', 'ISXM', 'ISXN', 'ISXO', 'ISXP', 'ISXQ',
  'ISXR', 'ISXS', 'ISXT', 'ISXU', 'ISXV', 'ISXW', 'ISXX', 'ISXY', 'ISXZ', 'ISY',
  'ISYB', 'ISYC', 'ISYD', 'ISYE', 'ISYF', 'ISYG', 'ISYH', 'ISYI', 'ISYJ', 'ISYK',
  'ISYL', 'ISYM', 'ISYN', 'ISYO', 'ISYP', 'ISYQ', 'ISYR', 'ISYS', 'ISYT', 'ISYU',
  'ISYV', 'ISYW', 'ISYX', 'ISYY', 'ISYZ', 'ISZ', 'ISZB', 'ISZC', 'ISZD', 'ISZE',
  'ISZF', 'ISZG', 'ISZH', 'ISZI', 'ISZJ', 'ISZK', 'ISZL', 'ISZM', 'ISZN', 'ISZO',
  'ISZP', 'ISZQ', 'ISZR', 'ISZS', 'ISZT', 'ISZU', 'ISZV', 'ISZW', 'ISZX', 'ISZY',
  // Expanded Russell 2000 - Real small-cap stocks (continued)
  'AAN', 'AAOI', 'AAON', 'AAT', 'AAWW', 'ABCB', 'ABG', 'ABM', 'ABR', 'ABUS',
  'ACAD', 'ACCO', 'ACEL', 'ACHC', 'ACHN', 'ACHR', 'ACIW', 'ACLS', 'ACMR', 'ACNB',
  'ACRE', 'ACRS', 'ACST', 'ACT', 'ACTG', 'ACU', 'ACV', 'ACVA', 'ACWI', 'ACWX',
  'ADAP', 'ADBE', 'ADCT', 'ADES', 'ADIL', 'ADMA', 'ADMP', 'ADNT', 'ADP', 'ADPT',
  'ADSK', 'ADTN', 'ADUS', 'ADV', 'ADVM', 'ADXN', 'AE', 'AEE', 'AEGN', 'AEHR',
  'AEIS', 'AEL', 'AEMD', 'AENZ', 'AEO', 'AEP', 'AER', 'AES', 'AESC', 'AEVA',
  'AEY', 'AEYE', 'AEZS', 'AFBI', 'AFCG', 'AFG', 'AFIB', 'AFLG', 'AFMD', 'AFRM',
  'AFT', 'AFYA', 'AG', 'AGBA', 'AGCO', 'AGD', 'AGE', 'AGEN', 'AGFS', 'AGI',
  'AGIO', 'AGL', 'AGLE', 'AGM', 'AGNC', 'AGO', 'AGR', 'AGRI', 'AGRO', 'AGRX',
  'AGS', 'AGTC', 'AGTI', 'AGX', 'AGYS', 'AHCO', 'AHH', 'AHI', 'AHL', 'AHPI',
  'AHR', 'AHT', 'AI', 'AIB', 'AIC', 'AIF', 'AIG', 'AIH', 'AIHS', 'AIM',
  'AIMC', 'AIMD', 'AIMDW', 'AIN', 'AINC', 'AINV', 'AIO', 'AIP', 'AIR', 'AIRC',
  'AIRG', 'AIRI', 'AIRR', 'AIRS', 'AIRT', 'AIRTP', 'AIT', 'AIU', 'AIV', 'AIZ',
  'AJG', 'AJRD', 'AJX', 'AKA', 'AKAM', 'AKAN', 'AKBA', 'AKO.A', 'AKO.B', 'AKR',
  'AKRO', 'AKTS', 'AKTX', 'AKU', 'AKUS', 'AKYA', 'AL', 'ALB', 'ALBO', 'ALC',
  'ALCC', 'ALCO', 'ALDX', 'ALE', 'ALEC', 'ALEX', 'ALG', 'ALGM', 'ALGN', 'ALGS',
  'ALGT', 'ALHC', 'ALIM', 'ALIT', 'ALJJ', 'ALK', 'ALKS', 'ALL', 'ALLE', 'ALLG',
  'ALLK', 'ALLO', 'ALLR', 'ALLT', 'ALLY', 'ALNA', 'ALNY', 'ALO', 'ALOR', 'ALORU',
  'ALORW', 'ALOT', 'ALPA', 'ALPAU', 'ALPAW', 'ALPN', 'ALPP', 'ALR', 'ALRM', 'ALRN',
  'ALRS', 'ALSA', 'ALSAR', 'ALSAU', 'ALSAW', 'ALSN', 'ALT', 'ALTG', 'ALTI', 'ALTO',
  'ALTR', 'ALTU', 'ALTUU', 'ALTUW', 'ALV', 'ALVO', 'ALVR', 'ALX', 'ALXO', 'ALYA',
  'ALZN', 'AM', 'AMAL', 'AMAM', 'AMAO', 'AMAOU', 'AMAOW', 'AMAT', 'AMBA', 'AMBC',
  'AMBO', 'AMBP', 'AMC', 'AMCR', 'AMCX', 'AMD', 'AME', 'AMED', 'AMEH', 'AMG',
  'AMGN', 'AMH', 'AMK', 'AMKR', 'AMLX', 'AMN', 'AMNB', 'AMOT', 'AMOV', 'AMP',
  'AMPE', 'AMPG', 'AMPH', 'AMPY', 'AMR', 'AMRC', 'AMRK', 'AMRN', 'AMRS', 'AMRX',
  'AMS', 'AMSC', 'AMSF', 'AMST', 'AMSWA', 'AMT', 'AMTB', 'AMTD', 'AMTI', 'AMTX',
  'AMWD', 'AMWL', 'AMX', 'AMYT', 'AMZN', 'AN', 'ANAB', 'ANDE', 'ANEB', 'ANET',
  'ANF', 'ANGH', 'ANGI', 'ANGN', 'ANGO', 'ANIK', 'ANIP', 'ANIX', 'ANNX', 'ANPC',
  'ANSS', 'ANTE', 'ANTX', 'ANVS', 'ANY', 'ANZU', 'ANZUU', 'ANZUW', 'AOD', 'AOGO',
  'AOGOU', 'AOGOW', 'AOMR', 'AON', 'AORT', 'AOS', 'AOSL', 'AOUT', 'AP', 'APA',
  'APAC', 'APACU', 'APACW', 'APAM', 'APCX', 'APD', 'APDN', 'APEI', 'APEN', 'APG',
  'APGB', 'APH', 'API', 'APLD', 'APLE', 'APLS', 'APLT', 'APM', 'APMI', 'APMIU',
  'APMIW', 'APO', 'APOG', 'APOP', 'APOS', 'APP', 'APPF', 'APPH', 'APPHW', 'APPN',
  'APPS', 'APR', 'APRE', 'APRN', 'APRT', 'APRX', 'APT', 'APTM', 'APTMU', 'APTMW',
  'APTO', 'APTS', 'APTV', 'APTX', 'APVO', 'APWC', 'APXI', 'APYX', 'AQB', 'AQMS',
  'AQN', 'AQNA', 'AQNB', 'AQNU', 'AQST', 'AQUA', 'AR', 'ARAV', 'ARAY', 'ARBE',
  'ARBEW', 'ARBG', 'ARBGU', 'ARBGW', 'ARBK', 'ARBKL', 'ARC', 'ARCB', 'ARCC', 'ARCE',
  'ARCH', 'ARCK', 'ARCKU', 'ARCKW', 'ARCO', 'ARCT', 'ARDC', 'ARDX', 'ARE', 'AREB',
  'AREBW', 'AREC', 'AREN', 'ARES', 'ARGD', 'ARGO', 'ARGX', 'ARHS', 'ARI', 'ARIS',
  'ARIZ', 'ARIZU', 'ARIZW', 'ARKO', 'ARKR', 'ARL', 'ARLO', 'ARLP', 'ARMK', 'ARMP',
  'ARMR', 'ARNC', 'AROC', 'AROW', 'ARQQ', 'ARQQW', 'ARQT', 'ARR', 'ARRW', 'ARRWU',
  'ARRWW', 'ARRY', 'ARTE', 'ARTEU', 'ARTEW', 'ARTL', 'ARTNA', 'ARTW', 'ARVL', 'ARVN',
  'ARW', 'ARWR', 'ARYD', 'ARYE', 'ASA', 'ASAI', 'ASAN', 'ASAP', 'ASB', 'ASBA',
  'ASC', 'ASCA', 'ASCAU', 'ASCAW', 'ASCB', 'ASCBR', 'ASCBU', 'ASCBW', 'ASG', 'ASGI',
  'ASGN', 'ASH', 'ASIX', 'ASLE', 'ASLN', 'ASM', 'ASMB', 'ASML', 'ASND', 'ASNS',
  'ASO', 'ASPA', 'ASPAU', 'ASPAW', 'ASPC', 'ASPCU', 'ASPCW', 'ASPN', 'ASPS', 'ASPU',
  'ASR', 'ASRT', 'ASRV', 'ASTC', 'ASTE', 'ASTH', 'ASTI', 'ASTL', 'ASTLW', 'ASTR',
  'ASTS', 'ASTSW', 'ASUR', 'ASX', 'ASXC', 'ASYS', 'ATAI', 'ATAK', 'ATAKU', 'ATAKW',
  'ATAQ', 'ATAX', 'ATCO', 'ATCOL', 'ATCO.PRH', 'ATCO.PRI', 'ATCX', 'ATEC', 'ATEN',
  'ATER', 'ATEX', 'ATGE', 'ATHA', 'ATHX', 'ATI', 'ATIF', 'ATIP', 'ATKR', 'ATLC',
  'ATLCL', 'ATLCP', 'ATLO', 'ATMR', 'ATMRU', 'ATMRW', 'ATNF', 'ATNFW', 'ATNI', 'ATNM',
  'ATNX', 'ATO', 'ATOM', 'ATOS', 'ATR', 'ATRA', 'ATRC', 'ATRI', 'ATRO', 'ATRS',
  'ATSG', 'ATTO', 'ATUS', 'ATVI', 'ATXI', 'ATXS', 'ATY', 'AU', 'AUB', 'AUBAP',
  'AUBN', 'AUD', 'AUDC', 'AUGX', 'AUID', 'AULT', 'AULT.PRD', 'AUMN', 'AUPH', 'AUR',
  'AURA', 'AURC', 'AURCU', 'AURCW', 'AUROW', 'AUS', 'AUST', 'AUTL', 'AUUD', 'AUVI',
  'AUY', 'AVA', 'AVAC', 'AVACU', 'AVACW', 'AVAH', 'AVAL', 'AVAN', 'AVAV', 'AVB',
  'AVCO', 'AVCT', 'AVCTW', 'AVD', 'AVDL', 'AVDX', 'AVEO', 'AVGO', 'AVGR', 'AVHI',
  'AVID', 'AVIR', 'AVK', 'AVNS', 'AVNT', 'AVNW', 'AVO', 'AVPT', 'AVRO', 'AVT',
  'AVTE', 'AVTR', 'AVTX', 'AVXL', 'AVY', 'AVYA', 'AWF', 'AWH', 'AWI', 'AWK',
  'AWP', 'AWR', 'AWRE', 'AWX', 'AX', 'AXAC', 'AXDX', 'AXGN', 'AXL', 'AXLA',
  'AXNX', 'AXON', 'AXP', 'AXR', 'AXS', 'AXSM', 'AXTA', 'AXTI', 'AXU', 'AY',
  'AYI', 'AYLA', 'AYRO', 'AYTU', 'AYX', 'AZ', 'AZEK', 'AZN', 'AZO', 'AZPN',
  'AZRE', 'AZTA', 'AZUL', 'AZYO', 'AZZ', 'B', 'BA', 'BABA', 'BAC', 'BACA',
  'BACK', 'BAER', 'BAERW', 'BAFN', 'BAH', 'BAK', 'BALY', 'BAM', 'BANC', 'BAND',
  'BANF', 'BANFP', 'BANR', 'BANX', 'BAOS', 'BAP', 'BARK', 'BASE', 'BATL', 'BATRA',
  'BATRK', 'BAX', 'BB', 'BBAI', 'BBAR', 'BBBY', 'BBCP', 'BBD', 'BBDC', 'BBDO',
  'BBGI', 'BBIO', 'BBLG', 'BBLGW', 'BBLN', 'BBN', 'BBQ', 'BBSI', 'BBU', 'BBUC',
  'BBVA', 'BBW', 'BBWI', 'BBY', 'BC', 'BCAB', 'BCAN', 'BCAT', 'BCBP', 'BCC',
  'BCDA', 'BCE', 'BCEL', 'BCH', 'BCLI', 'BCML', 'BCO', 'BCOR', 'BCOV', 'BCOW',
  'BCPC', 'BCRX', 'BCS', 'BCSA', 'BCSAU', 'BCSAW', 'BCSF', 'BCTX', 'BCV', 'BCX',
  'BCYC', 'BDC', 'BDJ', 'BDL', 'BDN', 'BDR', 'BDSX', 'BDTX', 'BDX', 'BDXB',
  'BE', 'BEAM', 'BEAT', 'BEATW', 'BECN', 'BEDU', 'BEEM', 'BEEMW', 'BEKE', 'BELFA',
  'BELFB', 'BEN', 'BENE', 'BENER', 'BENEU', 'BENEW', 'BEP', 'BEPC', 'BEPH', 'BEPI',
  'BERY', 'BEST', 'BF.A', 'BF.B', 'BFAC', 'BFAM', 'BFC', 'BFH', 'BFI', 'BFIIW',
  'BFIN', 'BFK', 'BFLY', 'BFRI', 'BFRIW', 'BFS', 'BFST', 'BFZ', 'BG', 'BGB',
  'BGCP', 'BGFV', 'BGH', 'BGI', 'BGNE', 'BGR', 'BGS', 'BGSX', 'BGT', 'BGX',
  'BGY', 'BH', 'BH.A', 'BHAC', 'BHACU', 'BHACW', 'BHAT', 'BHC', 'BHE', 'BHF',
  'BHFAL', 'BHFAM', 'BHFAN', 'BHFAO', 'BHFAP', 'BHG', 'BHIL', 'BHK', 'BHLB',
  'BHM', 'BHN', 'BHP', 'BHR', 'BHRB', 'BHRD', 'BHS', 'BHV', 'BHVN', 'BIAF',
  'BIAFW', 'BIDU', 'BIG', 'BIGC', 'BIGZ', 'BIIB', 'BILI', 'BILL', 'BIMI', 'BIO',
  'BIOC', 'BIOL', 'BIOR', 'BIOS', 'BIOSU', 'BIOSW', 'BIOX', 'BIP', 'BIPC', 'BIPH',
  'BIPI', 'BIRD', 'BIT', 'BITE', 'BITF', 'BIVI', 'BJ', 'BJDX', 'BJRI', 'BK',
  'BKCC', 'BKD', 'BKE', 'BKEP', 'BKEPP', 'BKH', 'BKI', 'BKKT', 'BKN', 'BKNG',
  'BKR', 'BKSC', 'BKSY', 'BKTX', 'BKU', 'BL', 'BLBD', 'BLBX', 'BLCM', 'BLCO',
  'BLCT', 'BLD', 'BLDE', 'BLDEW', 'BLDP', 'BLDR', 'BLE', 'BLFS', 'BLFY', 'BLIN',
  'BLK', 'BLKB', 'BLL', 'BLMN', 'BLND', 'BLNK', 'BLPH', 'BLRX', 'BLTE', 'BLU',
  'BLUA', 'BLUA.U', 'BLUA.WS', 'BLUE', 'BLW', 'BLX', 'BLZE', 'BMA', 'BMAC', 'BMAQ',
  'BMAQR', 'BMAQU', 'BMAQW', 'BMBL', 'BME', 'BMEA', 'BMEZ', 'BMI', 'BMLP', 'BMN',
  'BMO', 'BMRA', 'BMRC', 'BMRN', 'BMTC', 'BMY', 'BN', 'BNED', 'BNFT', 'BNGO',
  'BNIX', 'BNIXR', 'BNIXW', 'BNJ', 'BNL', 'BNNR', 'BNNRU', 'BNNRW', 'BNOX', 'BNR',
  'BNRE', 'BNRE.A', 'BNS', 'BNSO', 'BNTC', 'BNTX', 'BNY', 'BOAC', 'BOAS', 'BOC',
  'BOCN', 'BOCNU', 'BOCNW', 'BODY', 'BOE', 'BOH', 'BOKF', 'BOLT', 'BOMN', 'BON',
  'BOOM', 'BOOT', 'BORR', 'BOSC', 'BOTJ', 'BOWL', 'BOX', 'BOXD', 'BOXL', 'BP',
  'BPAC', 'BPACU', 'BPACW', 'BPC', 'BPFH', 'BPMC', 'BPOP', 'BPOPM', 'BPRN', 'BPT',
  'BPTH', 'BPTS', 'BPYPM', 'BPYPN', 'BPYPO', 'BPYPP', 'BQ', 'BR', 'BRAC', 'BRACR',
  'BRACU', 'BRACW', 'BRAG', 'BRBR', 'BRBS', 'BRC', 'BRCC', 'BRCN', 'BRD', 'BRDG',
  'BRDS', 'BREA', 'BREZ', 'BREZR', 'BREZW', 'BRF', 'BRFS', 'BRG', 'BRID', 'BRK.A',
  'BRK.B', 'BRKH', 'BRKHU', 'BRKHW', 'BRKL', 'BRKR', 'BRKY', 'BRLI', 'BRLIR',
  'BRLIU', 'BRLIW', 'BRMK', 'BRN', 'BRO', 'BROG', 'BROS', 'BRP', 'BRQS', 'BRSP',
  'BRT', 'BRW', 'BRX', 'BRY', 'BRZE', 'BSAC', 'BSAQ', 'BSBK', 'BSBR', 'BSET',
  'BSFC', 'BSGA', 'BSGAR', 'BSGAU', 'BSGAW', 'BSGM', 'BSIG', 'BSL', 'BSM', 'BSMX',
  'BSQR', 'BSRR', 'BST', 'BSTZ', 'BSV', 'BSVN', 'BSX', 'BSY', 'BTA', 'BTB',
  'BTBD', 'BTBDW', 'BTBT', 'BTCM', 'BTCS', 'BTCY', 'BTG', 'BTI', 'BTN', 'BTO',
  'BTRS', 'BTRSW', 'BTT', 'BTTR', 'BTTRW', 'BTTX', 'BTU', 'BTWN', 'BTWNU', 'BTWNW',
  'BTZ', 'BUD', 'BUI', 'BUR', 'BURL', 'BUSE', 'BV', 'BVH', 'BVN', 'BVS',
  'BVXV', 'BW', 'BWA', 'BWAC', 'BWACU', 'BWACW', 'BWAY', 'BWB', 'BWBBP', 'BWC',
  'BWCAU', 'BWCAW', 'BWEN', 'BWFG', 'BWG', 'BWMN', 'BWMX', 'BWNB', 'BWSN', 'BWV',
  'BWX', 'BWXT', 'BWZ', 'BX', 'BXC', 'BXMT', 'BXMX', 'BXP', 'BXRX', 'BXSL',
  'BY', 'BYD', 'BYFC', 'BYM', 'BYN', 'BYND', 'BYNO', 'BYNOU', 'BYNOW', 'BYRN',
  'BYSI', 'BYTS', 'BYTSU', 'BYTSW', 'BZ', 'BZFD', 'BZH', 'BZUN', 'C', 'CAAP',
  'CAAS', 'CABA', 'CABO', 'CAC', 'CACC', 'CACI', 'CADE', 'CADL', 'CAE', 'CAF',
  'CAG', 'CAH', 'CAJ', 'CAKE', 'CAL', 'CALB', 'CALC', 'CALF', 'CALM', 'CALT',
  'CALX', 'CAMP', 'CAMT', 'CAN', 'CANB', 'CANF', 'CANG', 'CANO', 'CAPL', 'CAPR',
  'CAR', 'CARA', 'CARE', 'CARG', 'CARM', 'CARR', 'CARS', 'CARV', 'CAS', 'CASA',
  'CASH', 'CASI', 'CASS', 'CASY', 'CAT', 'CATC', 'CATO', 'CATX', 'CATY', 'CB',
  'CBAN', 'CBAT', 'CBAY', 'CBB', 'CBD', 'CBFV', 'CBH', 'CBIO', 'CBL', 'CBNK',
  'CBOE', 'CBON', 'CBRG', 'CBRGU', 'CBRGW', 'CBRL', 'CBRT', 'CBSH', 'CBT', 'CBU',
  'CBUS', 'CBZ', 'CC', 'CCAI', 'CCAIU', 'CCAIW', 'CCAP', 'CCB', 'CCBG', 'CCCC',
  'CCCS', 'CCD', 'CCEL', 'CCEP', 'CCF', 'CCI', 'CCIF', 'CCJ', 'CCK', 'CCL',
  'CCLP', 'CCM', 'CCNE', 'CCNEP', 'CCO', 'CCOI', 'CCOR', 'CCRN', 'CCS', 'CCSI',
  'CCU', 'CCV', 'CCVI', 'CCXI', 'CCZ', 'CD', 'CDAK', 'CDAQ', 'CDAQU', 'CDAQW',
  'CDAY', 'CDE', 'CDEV', 'CDIO', 'CDIOW', 'CDLX', 'CDMO', 'CDNA', 'CDNS', 'CDR',
  'CDRE', 'CDRO', 'CDTX', 'CDW', 'CDXC', 'CDXS', 'CDZI', 'CE', 'CEA', 'CECE',
  'CECO', 'CEE', 'CEF', 'CEG', 'CEI', 'CEIX', 'CELC', 'CELH', 'CELU', 'CELZ',
  'CEM', 'CEMI', 'CEN', 'CENQ', 'CENQU', 'CENQW', 'CENT', 'CENTA', 'CENX', 'CEPU',
  'CEQP', 'CERC', 'CERE', 'CERS', 'CERT', 'CET', 'CETU', 'CETUW', 'CETX', 'CEV',
  'CEVA', 'CF', 'CFA', 'CFB', 'CFBK', 'CFFE', 'CFFI', 'CFFN', 'CFFS', 'CFG',
  'CFIV', 'CFIVU', 'CFIVW', 'CFLT', 'CFMS', 'CFR', 'CFRX', 'CFSB', 'CG', 'CGA',
  'CGAU', 'CGBD', 'CGC', 'CGEM', 'CGEN', 'CGNT', 'CGNX', 'CGO', 'CGRN', 'CGTX',
  'CGUS', 'CGUSU', 'CGUSW', 'CHAA', 'CHCI', 'CHCO', 'CHCT', 'CHD', 'CHDN', 'CHE',
  'CHEA', 'CHEAU', 'CHEAW', 'CHEF', 'CHEK', 'CHGG', 'CHH', 'CHI', 'CHK', 'CHKP',
  'CHMG', 'CHMI', 'CHN', 'CHNR', 'CHPT', 'CHRA', 'CHRB', 'CHRD', 'CHRS', 'CHRW',
  'CHS', 'CHT', 'CHUY', 'CHW', 'CHWY', 'CHX', 'CHY', 'CI', 'CIA', 'CIB', 'CIDM',
  'CIEN', 'CIF', 'CIFR', 'CIG', 'CIG.C', 'CIGI', 'CIH', 'CII', 'CIIG', 'CIIGU',
  'CIIGW', 'CIK', 'CIM', 'CINC', 'CING', 'CINT', 'CIO', 'CION', 'CIR', 'CISO',
  'CITE', 'CITEU', 'CITEW', 'CIVB', 'CIX', 'CIZN', 'CJJD', 'CKPT', 'CKX', 'CL',
  'CLAR', 'CLAY', 'CLAYU', 'CLAYW', 'CLB', 'CLBK', 'CLBR', 'CLBT', 'CLDT', 'CLDX',
  'CLEU', 'CLF', 'CLFD', 'CLGN', 'CLH', 'CLI', 'CLIM', 'CLIR', 'CLLS', 'CLM',
  'CLMB', 'CLMT', 'CLNE', 'CLNN', 'CLNNW', 'CLOE', 'CLOV', 'CLPR', 'CLPS', 'CLPT',
  'CLRB', 'CLRC', 'CLRCU', 'CLRCW', 'CLRO', 'CLS', 'CLSD', 'CLSK', 'CLST', 'CLVR',
  'CLVRW', 'CLVS', 'CLVT', 'CLW', 'CLWT', 'CLX', 'CLXT', 'CM', 'CMA', 'CMAX',
  'CMAXW', 'CMBM', 'CMBS', 'CMC', 'CMCA', 'CMCAU', 'CMCAW', 'CMCL', 'CMCM', 'CMCO',
  'CMCT', 'CME', 'CMG', 'CMI', 'CMLS', 'CMMB', 'CMO', 'CMP', 'CMPO', 'CMPR',
  'CMPS', 'CMPX', 'CMRA', 'CMRE', 'CMRX', 'CMS', 'CMSA', 'CMSC', 'CMSD', 'CMTL',
  'CMU', 'CNA', 'CNC', 'CNCE', 'CND', 'CNDA', 'CNDB', 'CNDT', 'CNET', 'CNEY',
  'CNF', 'CNFR', 'CNGL', 'CNHI', 'CNI', 'CNK', 'CNM', 'CNMD', 'CNNE', 'CNO',
  'CNOB', 'CNP', 'CNQ', 'CNR', 'CNS', 'CNSP', 'CNST', 'CNTA', 'CNTB', 'CNTG',
  'CNTY', 'CNX', 'CNXC', 'CNXN', 'CO', 'COCO', 'COCP', 'CODA', 'CODI', 'CODX',
  'COE', 'COF', 'COFS', 'COGT', 'COHN', 'COHR', 'COHU', 'COIN', 'COKE', 'COLB',
  'COLD', 'COLI', 'COLL', 'COLM', 'COMM', 'COMO', 'COMP', 'COMS', 'CONE', 'CONN',
  'CONX', 'CONXU', 'CONXW', 'COO', 'COOK', 'COOL', 'COOLU', 'COOLW', 'COOP', 'COP',
  'CORR', 'CORS', 'CORT', 'CORZ', 'COSM', 'COST', 'COTY', 'COUR', 'COVA', 'COVAU',
  'COVAW', 'COWN', 'COWNL', 'CP', 'CPA', 'CPAA', 'CPAC', 'CPAR', 'CPARU', 'CPARW',
  'CPB', 'CPE', 'CPF', 'CPG', 'CPHC', 'CPHI', 'CPIX', 'CPK', 'CPLP', 'CPNG',
  'CPOP', 'CPRT', 'CPRX', 'CPS', 'CPSH', 'CPSI', 'CPSS', 'CPT', 'CPTA', 'CPTK',
  'CPTN', 'CPUH', 'CPZ', 'CQP', 'CQQQ', 'CR', 'CRAI', 'CRBP', 'CRBU', 'CRC',
  'CRCT', 'CRD.A', 'CRD.B', 'CRDF', 'CRDL', 'CRDO', 'CREC', 'CREG', 'CRESY', 'CREX',
  'CREXW', 'CRF', 'CRGE', 'CRGY', 'CRH', 'CRHC', 'CRI', 'CRIS', 'CRK', 'CRKN',
  'CRL', 'CRM', 'CRMD', 'CRMT', 'CRNC', 'CRNT', 'CRNX', 'CRON', 'CROX', 'CRS',
  'CRSP', 'CRSR', 'CRT', 'CRTD', 'CRTDW', 'CRTO', 'CRTX', 'CRU', 'CRUS', 'CRVL',
  'CRVS', 'CRWD', 'CRWS', 'CRXT', 'CRY', 'CRZN', 'CRZNU', 'CRZNW', 'CS', 'CSAN',
  'CSBR', 'CSCO', 'CSCW', 'CSGP', 'CSGS', 'CSHI', 'CSII', 'CSIQ', 'CSL', 'CSLM',
  'CSLT', 'CSML', 'CSPI', 'CSQ', 'CSR', 'CSSE', 'CSSEN', 'CSSEP', 'CSTA', 'CSTE',
  'CSTL', 'CSTM', 'CSTR', 'CSU', 'CSV', 'CSWC', 'CSWI', 'CSX', 'CTAS', 'CTBI',
  'CTEK', 'CTG', 'CTHR', 'CTIB', 'CTIC', 'CTKB', 'CTLP', 'CTLT', 'CTMX', 'CTO',
  'CTOS', 'CTR', 'CTRA', 'CTRE', 'CTRM', 'CTRN', 'CTS', 'CTSH', 'CTSO', 'CTT',
  'CTVA', 'CTXR', 'CTXS', 'CUBA', 'CUBE', 'CUBI', 'CUE', 'CUEN', 'CUK', 'CULP',
  'CURI', 'CURIW', 'CURO', 'CURV', 'CUTR', 'CUZ', 'CVAC', 'CVBF', 'CVCO', 'CVCY',
  'CVE', 'CVEO', 'CVET', 'CVGI', 'CVGW', 'CVI', 'CVII', 'CVII.U', 'CVII.WS', 'CVLG',
  'CVLT', 'CVLY', 'CVM', 'CVNA', 'CVR', 'CVRX', 'CVS', 'CVT', 'CVU', 'CVV',
  'CVX', 'CW', 'CWAN', 'CWBC', 'CWCO', 'CWEN', 'CWH', 'CWK', 'CWST', 'CWT',
  'CX', 'CXAC', 'CXDO', 'CXE', 'CXH', 'CXM', 'CXW', 'CYAD', 'CYAN', 'CYBE',
  'CYBR', 'CYCC', 'CYCN', 'CYD', 'CYH', 'CYN', 'CYRX', 'CYT', 'CYTH', 'CYTK',
  'CYTO', 'CYXT', 'CZFS', 'CZNC', 'CZR', 'CZWI', 'D', 'DAC', 'DADA', 'DAIO',
  'DAKT', 'DAL', 'DAN', 'DAO', 'DAR', 'DARE', 'DASH', 'DAVA', 'DAVE', 'DAWN',
  'DB', 'DBD', 'DBI', 'DBL', 'DBRG', 'DBTX', 'DBVT', 'DBX', 'DC', 'DCBO',
  'DCFC', 'DCFCW', 'DCI', 'DCO', 'DCOM', 'DCP', 'DCPH', 'DCT', 'DCUE', 'DD',
  'DDD', 'DDI', 'DDL', 'DDOG', 'DDS', 'DDT', 'DE', 'DEA', 'DECK', 'DEI',
  'DELL', 'DEN', 'DENN', 'DEO', 'DERM', 'DESP', 'DEX', 'DFFN', 'DFH', 'DFIN',
  'DFP', 'DFS', 'DG', 'DGHI', 'DGICA', 'DGICB', 'DGII', 'DGLY', 'DGNU', 'DGX',
  'DH', 'DHAC', 'DHACU', 'DHACW', 'DHC', 'DHCA', 'DHCAU', 'DHCAW', 'DHCNI', 'DHCNL',
  'DHF', 'DHI', 'DHIL', 'DHR', 'DHT', 'DHX', 'DHY', 'DIAX', 'DIBS', 'DICE',
  'DIN', 'DINO', 'DIOD', 'DIS', 'DISA', 'DISAU', 'DISAW', 'DISH', 'DIT', 'DJCO',
  'DK', 'DKDCA', 'DKDCU', 'DKL', 'DKNG', 'DKS', 'DLA', 'DLB', 'DLCA', 'DLCAU',
  'DLCAW', 'DLHC', 'DLNG', 'DLO', 'DLPN', 'DLR', 'DLTH', 'DLTR', 'DLX', 'DLY',
  'DM', 'DMA', 'DMAC', 'DMACU', 'DMACW', 'DMAQ', 'DMB', 'DMF', 'DMLP', 'DMO',
  'DMRC', 'DMS', 'DMTK', 'DMYY', 'DNA', 'DNAA', 'DNAB', 'DNAD', 'DNB', 'DNLI',
  'DNMR', 'DNOW', 'DNP', 'DNUT', 'DO', 'DOC', 'DOCN', 'DOCS', 'DOCU', 'DOGZ',
  'DOLE', 'DOMA', 'DOMH', 'DOMO', 'DOOO', 'DOOR', 'DORM', 'DOUG', 'DOV', 'DOW',
  'DOX', 'DOYU', 'DPCS', 'DPG', 'DPRO', 'DPSI', 'DPZ', 'DQ', 'DRCT', 'DRCTW',
  'DRD', 'DRE', 'DRH', 'DRI', 'DRIO', 'DRMA', 'DRMAW', 'DRQ', 'DRRX', 'DRS',
  'DRTS', 'DRTSW', 'DRTT', 'DRUG', 'DRVN', 'DS', 'DSAQ', 'DSEY', 'DSGN', 'DSGR',
  'DSGX', 'DSKE', 'DSL', 'DSM', 'DSP', 'DSS', 'DSU', 'DSWL', 'DSX', 'DT',
  'DTB', 'DTC', 'DTE', 'DTF', 'DTIL', 'DTM', 'DTOC', 'DTOCU', 'DTOCW', 'DTRT',
  'DTSS', 'DTST', 'DTSTW', 'DUET', 'DUETU', 'DUETW', 'DUNE', 'DUNEU', 'DUNEW',
  'DUO', 'DUOL', 'DUOT', 'DV', 'DVA', 'DVAX', 'DVN', 'DWAC', 'DWACU', 'DWACW',
  'DWIN', 'DWSN', 'DX', 'DXC', 'DXF', 'DXPE', 'DXR', 'DXYN', 'DY', 'DYAI',
  'DYN', 'DYNT', 'DZSI', 'E', 'EA', 'EAC', 'EAD', 'EAF', 'EAI', 'EAR',
  'EARN', 'EARS', 'EAST', 'EAT', 'EB', 'EBAY', 'EBC', 'EBET', 'EBF', 'EBIX',
  'EBMT', 'EBON', 'EBR', 'EBS', 'EBTC', 'EC', 'ECC', 'ECCC', 'ECCV', 'ECCW',
  'ECCX', 'ECF', 'ECHO', 'ECL', 'ECOL', 'ECOM', 'ECOR', 'ECPG', 'ECVT', 'ED',
  'EDAP', 'EDBL', 'EDD', 'EDF', 'EDI', 'EDIT', 'EDN', 'EDR', 'EDRY', 'EDSA',
  'EDTK', 'EDU', 'EDUC', 'EE', 'EEA', 'EEFT', 'EEIQ', 'EEX', 'EFC', 'EFHT',
  'EFOI', 'EFR', 'EFSC', 'EFSH', 'EFT', 'EFTR', 'EFX', 'EGAN', 'EGBN', 'EGF',
  'EGGF', 'EGHT', 'EGIO', 'EGLE', 'EGLX', 'EGO', 'EGOV', 'EGP', 'EGRX', 'EGY',
  'EH', 'EHC', 'EHI', 'EHTH', 'EIC', 'EICA', 'EIG', 'EIGR', 'EIM', 'EIX',
  'EJH', 'EKSO', 'EL', 'ELA', 'ELAN', 'ELBM', 'ELC', 'ELDN', 'ELEV', 'ELF',
  'ELLO', 'ELMD', 'ELME', 'ELOX', 'ELP', 'ELS', 'ELSE', 'ELTK', 'ELV', 'ELVN',
  'ELVT', 'ELYM', 'ELYS', 'EM', 'EMAN', 'EMBC', 'EMBK', 'EMCF', 'EMD', 'EME',
  'EMF', 'EMKR', 'EML', 'EMN', 'EMO', 'EMP', 'EMR', 'EMX', 'ENB', 'ENBA',
  'ENCP', 'ENCP.U', 'ENCP.WS', 'ENDP', 'ENER', 'ENFN', 'ENG', 'ENIC', 'ENJ',
  'ENLC', 'ENLT', 'ENLV', 'ENO', 'ENOB', 'ENOV', 'ENPH', 'ENR', 'ENS', 'ENSG',
  'ENSV', 'ENTA', 'ENTF', 'ENTG', 'ENTX', 'ENV', 'ENVA', 'ENVB', 'ENVI', 'ENVIU',
  'ENVIW', 'ENVX', 'ENX', 'ENZ', 'EOD', 'EOG', 'EOI', 'EOLS', 'EOS', 'EOSE',
  'EOT', 'EP', 'EPAC', 'EPAM', 'EPAY', 'EPC', 'EPD', 'EPHY', 'EPIX', 'EPM',
  'EPOW', 'EPR', 'EPRT', 'EPSN', 'EPWR', 'EPZM', 'EQ', 'EQBK', 'EQC', 'EQD',
  'EQH', 'EQHA', 'EQIX', 'EQNR', 'EQR', 'EQS', 'EQT', 'EQX', 'ERAS', 'ERC',
  'ERES', 'ERESU', 'ERESW', 'ERF', 'ERH', 'ERIC', 'ERIE', 'ERII', 'ERJ', 'ERO',
  'ERYP', 'ES', 'ESAB', 'ESAC', 'ESACU', 'ESACW', 'ESBA', 'ESCA', 'ESE', 'ESEA',
  'ESGR', 'ESGRO', 'ESGRP', 'ESI', 'ESLT', 'ESM', 'ESMT', 'ESNT', 'ESOA', 'ESP',
  'ESPR', 'ESQ', 'ESRT', 'ESS', 'ESSA', 'ESSC', 'ESSCR', 'ESSCU', 'ESSCW', 'ESTA',
  'ESTC', 'ESTE', 'ET', 'ETAC', 'ETACU', 'ETACW', 'ETB', 'ETD', 'ETE', 'ETG',
  'ETH', 'ETI', 'ETJ', 'ETN', 'ETNB', 'ETO', 'ETON', 'ETR', 'ETRN', 'ETSY',
  'ETV', 'ETW', 'ETWO', 'ETX', 'ETY', 'EU', 'EUCR', 'EUCRU', 'EUCRW', 'EUFN',
  'EURN', 'EVA', 'EVAX', 'EVBG', 'EVBN', 'EVC', 'EVCM', 'EVE', 'EVER', 'EVEX',
  'EVF', 'EVFM', 'EVG', 'EVGN', 'EVGO', 'EVGR', 'EVGRU', 'EVGRW', 'EVH', 'EVI',
  'EVK', 'EVLO', 'EVLV', 'EVM', 'EVN', 'EVO', 'EVOK', 'EVOP', 'EVR', 'EVRG',
  'EVRI', 'EVT', 'EVTC', 'EVTL', 'EVTV', 'EVV', 'EW', 'EWA', 'EWBC', 'EWC',
  'EWD', 'EWG', 'EWH', 'EWI', 'EWJ', 'EWK', 'EWL', 'EWM', 'EWN', 'EWO',
  'EWP', 'EWQ', 'EWS', 'EWT', 'EWU', 'EWV', 'EWW', 'EWY', 'EWZ', 'EXAS',
  'EXC', 'EXD', 'EXEL', 'EXFY', 'EXG', 'EXK', 'EXLS', 'EXN', 'EXP', 'EXPD',
  'EXPE', 'EXPI', 'EXPO', 'EXPR', 'EXR', 'EXTR', 'EYE', 'EYEN', 'EYES', 'EYPT',
  'EZFL', 'EZGO', 'EZJ', 'EZM', 'EZPW', 'F', 'FA', 'FACA', 'FACT', 'FAF',
  'FAM', 'FAMI', 'FANH', 'FARM', 'FARO', 'FAST', 'FAT', 'FATBB', 'FATBP',
  'FATBW', 'FATE', 'FATH', 'FATP', 'FATPU', 'FATPW', 'FAX', 'FAZE', 'FAZEW',
  'FB', 'FBC', 'FBHS', 'FBIO', 'FBK', 'FBM', 'FBMS', 'FBNC', 'FBP', 'FBRT',
  'FBRX', 'FBT', 'FBZ', 'FC', 'FCAP', 'FCAX', 'FCBC', 'FCCO', 'FCCY', 'FCEL',
  'FCF', 'FCFS', 'FCN', 'FCNCA', 'FCNCO', 'FCNCP', 'FCO', 'FCPT', 'FCRD', 'FCRX',
  'FCT', 'FCUV', 'FCX', 'FDBC', 'FDEU', 'FDHY', 'FDIS', 'FDMT', 'FDP', 'FDRV',
  'FDS', 'FDUS', 'FDX', 'FE', 'FEAM', 'FEDU', 'FEI', 'FEIM', 'FELE', 'FEM',
  'FEMY', 'FEN', 'FENC', 'FENG', 'FENY', 'FEO', 'FEP', 'FERG', 'FET', 'FEUS',
  'FEUZ', 'FEX', 'FEYE', 'FF', 'FFA', 'FFBC', 'FFC', 'FFEB', 'FFHG', 'FFIC',
  'FFIE', 'FFIN', 'FFIV', 'FFNW', 'FFWM', 'FGB', 'FGBI', 'FGEN', 'FGF', 'FGI',
  'FGMC', 'FGN', 'FGP', 'FGR', 'FGRO', 'FHB', 'FHI', 'FHLT', 'FHN', 'FHTX',
  'FHYS', 'FI', 'FIA', 'FIBK', 'FICO', 'FICV', 'FID', 'FIDI', 'FIF', 'FIG',
  'FIGS', 'FILL', 'FINV', 'FINW', 'FIP', 'FIS', 'FISI', 'FISK', 'FISR', 'FISV',
  'FIT', 'FITE', 'FIV', 'FIVE', 'FIX', 'FIXD', 'FIXX', 'FIZZ', 'FJUL', 'FJUN',
  'FKU', 'FL', 'FLAG', 'FLAX', 'FLBL', 'FLC', 'FLEX', 'FLFV', 'FLGC', 'FLGT',
  'FLIC', 'FLJ', 'FLL', 'FLME', 'FLMI', 'FLNC', 'FLNG', 'FLNT', 'FLO', 'FLR',
  'FLS', 'FLT', 'FLUX', 'FLWS', 'FLXS', 'FLYW', 'FM', 'FMAC', 'FMAC.U', 'FMAC.WS',
  'FMAO', 'FMAR', 'FMAY', 'FMB', 'FMBH', 'FMC', 'FMHI', 'FMIL', 'FMN', 'FMNB',
  'FMNY', 'FMO', 'FMX', 'FMY', 'FN', 'FNA', 'FNB', 'FNCB', 'FNCH', 'FNCL',
  'FND', 'FNDA', 'FNDB', 'FNDC', 'FNDE', 'FNDF', 'FNDX', 'FNF', 'FNGR', 'FNHC',
  'FNKO', 'FNLC', 'FNMA', 'FNOV', 'FNV', 'FNWB', 'FNWD', 'FNX', 'FNY', 'FOA',
  'FOCS', 'FOCT', 'FOF', 'FONR', 'FOR', 'FORA', 'FORD', 'FORG', 'FORM', 'FORR',
  'FORT', 'FOSL', 'FOVL', 'FOX', 'FOXA', 'FOXF', 'FOXW', 'FPAC', 'FPAC.U',
  'FPAC.WS', 'FPFD', 'FPH', 'FPI', 'FPL', 'FPRX', 'FPX', 'FPXE', 'FPXI', 'FQAL',
  'FR', 'FRA', 'FRAF', 'FRBA', 'FRBK', 'FRBN', 'FRD', 'FREE', 'FREEW', 'FREQ',
  'FREY', 'FRG', 'FRGE', 'FRGI', 'FRGT', 'FRHC', 'FRLA', 'FRLAU', 'FRLAW', 'FRLN',
  'FRME', 'FRMEP', 'FRO', 'FRON', 'FROS', 'FRPH', 'FRPT', 'FRSH', 'FRST', 'FRSX',
  'FRT', 'FRTA', 'FRW', 'FRWAU', 'FRWAW', 'FRXB', 'FRZA', 'FSBC', 'FSBW', 'FSCO',
  'FSD', 'FSEA', 'FSEC', 'FSEP', 'FSFG', 'FSI', 'FSIG', 'FSK', 'FSLR', 'FSLY',
  'FSM', 'FSNB', 'FSP', 'FSR', 'FSRX', 'FSS', 'FSTA', 'FSTR', 'FSTX', 'FSV',
  'FT', 'FTA', 'FTAG', 'FTAI', 'FTAIN', 'FTAIO', 'FTAIP', 'FTCH', 'FTCI', 'FTCS',
  'FTDR', 'FTEK', 'FTF', 'FTFT', 'FTGC', 'FTHI', 'FTHM', 'FTHY', 'FTI', 'FTII',
  'FTK', 'FTLS', 'FTPA', 'FTS', 'FTSI', 'FTV', 'FTXG', 'FTXH', 'FTXL', 'FTXN',
  'FTXO', 'FTXR', 'FUBO', 'FUL', 'FULC', 'FULT', 'FULTP', 'FUN', 'FUNC', 'FUND',
  'FUNL', 'FURY', 'FUSB', 'FUSN', 'FUTU', 'FUTY', 'FUV', 'FV', 'FVAL', 'FVC',
  'FVCB', 'FVD', 'FVE', 'FVL', 'FVRR', 'FVT', 'FWAC', 'FWAC.U', 'FWAC.WS', 'FWBI',
  'FWP', 'FWRD', 'FWRG', 'FXA', 'FXB', 'FXC', 'FXD', 'FXE', 'FXF', 'FXG',
  'FXH', 'FXI', 'FXL', 'FXN', 'FXO', 'FXP', 'FXR', 'FXU', 'FXY', 'FXZ',
  'FYBR', 'FYC', 'FYLD', 'FYT', 'FYX', 'FZT', 'G', 'GAB', 'GABC', 'GABF',
  'GAIA', 'GAIN', 'GAINL', 'GAINN', 'GAINZ', 'GALT', 'GAM', 'GAMB', 'GAMC', 'GAME',
  'GAN', 'GANX', 'GAPA', 'GAPA.U', 'GAPA.WS', 'GASS', 'GATE', 'GATE.U', 'GATE.WS',
  'GATO', 'GATX', 'GAU', 'GB', 'GBAB', 'GBBK', 'GBDC', 'GBIL', 'GBIO', 'GBLD',
  'GBLI', 'GBLL', 'GBNH', 'GBNY', 'GBR', 'GBRG', 'GBS', 'GBT', 'GBX', 'GCBC',
  'GCC', 'GCI', 'GCMG', 'GCO', 'GCP', 'GCV', 'GD', 'GDDY', 'GDEN', 'GDEV',
  'GDEVW', 'GDF', 'GDL', 'GDNR', 'GDO', 'GDOT', 'GDS', 'GDST', 'GDV', 'GDVD',
  'GDX', 'GDXJ', 'GDYN', 'GE', 'GECC', 'GECCM', 'GECCN', 'GECCO', 'GECCZ', 'GEEX',
  'GEF', 'GEG', 'GEHC', 'GEHC.U', 'GEHC.WS', 'GEL', 'GEM', 'GEN', 'GENC', 'GENE',
  'GENI', 'GENQ', 'GEO', 'GEOS', 'GER', 'GERN', 'GES', 'GET', 'GETR', 'GETY',
  'GEVO', 'GF', 'GFAI', 'GFF', 'GFI', 'GFL', 'GFOR', 'GFS', 'GFX', 'GGAL',
  'GGB', 'GGG', 'GGN', 'GGO', 'GGR', 'GGT', 'GGZ', 'GH', 'GHC', 'GHG',
  'GHL', 'GHLD', 'GHM', 'GHRS', 'GHSI', 'GHY', 'GIA', 'GIB', 'GIC', 'GIFI',
  'GIGM', 'GII', 'GIII', 'GIL', 'GILD', 'GILT', 'GIM', 'GINN', 'GIPR', 'GIS',
  'GIW', 'GJH', 'GJO', 'GJP', 'GJR', 'GJS', 'GJT', 'GKOS', 'GL', 'GLAD',
  'GLBE', 'GLBL', 'GLBS', 'GLBZ', 'GLDD', 'GLDG', 'GLEE', 'GLG', 'GLHA', 'GLIF',
  'GLIN', 'GLL', 'GLMD', 'GLNG', 'GLO', 'GLOB', 'GLOG', 'GLOP', 'GLP', 'GLPG',
  'GLPI', 'GLQ', 'GLRE', 'GLS', 'GLSI', 'GLST', 'GLT', 'GLTO', 'GLTR', 'GLU',
  'GLUE', 'GLV', 'GLXZ', 'GM', 'GMAB', 'GMBL', 'GMBT', 'GMDA', 'GME', 'GMED',
  'GMF', 'GMOM', 'GMPR', 'GMRE', 'GMS', 'GMTX', 'GMVD', 'GNAC', 'GNACU', 'GNACW',
  'GNCA', 'GNE', 'GNK', 'GNL', 'GNLN', 'GNMK', 'GNOM', 'GNPX', 'GNR', 'GNRC',
  'GNS', 'GNSS', 'GNT', 'GNTA', 'GNTX', 'GNTY', 'GNUS', 'GNW', 'GO', 'GOCO',
  'GOED', 'GOEV', 'GOEVW', 'GOEX', 'GOF', 'GOGL', 'GOGN', 'GOGO', 'GOL', 'GOLD',
  'GOLF', 'GOOD', 'GOOG', 'GOOGL', 'GOOS', 'GORO', 'GOSS', 'GOTU', 'GOVX', 'GOVZ',
  'GP', 'GPAC', 'GPACU', 'GPACW', 'GPC', 'GPCR', 'GPI', 'GPJA', 'GPK', 'GPL',
  'GPM', 'GPMT', 'GPN', 'GPOR', 'GPP', 'GPRE', 'GPRK', 'GPRO', 'GPS', 'GPX',
  'GQRE', 'GQSI', 'GRAB', 'GRABW', 'GRAY', 'GRBK', 'GRC', 'GRCL', 'GRCY', 'GREE',
  'GREI', 'GREK', 'GRES', 'GRF', 'GRFS', 'GRID', 'GRIF', 'GRIL', 'GRIN', 'GRMN',
  'GRN', 'GRNA', 'GRNB', 'GRND', 'GRNE', 'GRNQ', 'GROV', 'GROW', 'GROY', 'GRP',
  'GRPH', 'GRPN', 'GRRR', 'GRTS', 'GRTX', 'GRU', 'GRVY', 'GRWG', 'GRX', 'GRYB',
  'GS', 'GSAH', 'GSAT', 'GSBC', 'GSBD', 'GSC', 'GSD', 'GSEU', 'GSEW', 'GSG',
  'GSHD', 'GSID', 'GSIE', 'GSIG', 'GSIT', 'GSJY', 'GSK', 'GSKY', 'GSL', 'GSLC',
  'GSM', 'GSMG', 'GSMGW', 'GSP', 'GSPY', 'GSQB', 'GSSC', 'GSS', 'GST', 'GSUM',
  'GSUS', 'GSV', 'GSY', 'GT', 'GTAC', 'GTACU', 'GTACW', 'GTBP', 'GTE', 'GTEC',
  'GTES', 'GTH', 'GTHX', 'GTIM', 'GTIP', 'GTLS', 'GTN', 'GTO', 'GTR', 'GTX',
  'GTXAP', 'GTY', 'GUG', 'GUNR', 'GURE', 'GURU', 'GUSA', 'GUSH', 'GUT', 'GUTS',
  'GVA', 'GVAL', 'GVI', 'GVIP', 'GVP', 'GWB', 'GWGH', 'GWRE', 'GWRS', 'GWW',
  'GWX', 'GXC', 'GXF', 'GXG', 'GXTG', 'GYLD', 'GYRO', 'H', 'HA', 'HAE',
  'HAFC', 'HAIA', 'HAIAU', 'HAIAW', 'HAIN', 'HAL', 'HALL', 'HALO', 'HAP', 'HAPI',
  'HAPP', 'HAPY', 'HARD', 'HARP', 'HART', 'HAS', 'HASI', 'HAUS', 'HAWX', 'HAYN',
  'HAYW', 'HBB', 'HBCP', 'HBI', 'HBIO', 'HBM', 'HBMD', 'HBNC', 'HBT', 'HCA',
  'HCAT', 'HCC', 'HCCI', 'HCDI', 'HCDIP', 'HCI', 'HCKT', 'HCM', 'HCNE', 'HCOM',
  'HCP', 'HCRB', 'HCSG', 'HCTI', 'HCVI', 'HCVIU', 'HCVIW', 'HCWB', 'HCXY', 'HD',
  'HDAW', 'HDB', 'HDEF', 'HDG', 'HDGE', 'HDLB', 'HDMV', 'HDRO', 'HDSN', 'HDV',
  'HDWX', 'HE', 'HEAR', 'HEDJ', 'HEEM', 'HEES', 'HEFA', 'HEGD', 'HEI', 'HELE',
  'HELX', 'HEP', 'HEPA', 'HEPS', 'HEQ', 'HEQT', 'HERD', 'HERO', 'HES', 'HESM',
  'HEWG', 'HEWI', 'HEWJ', 'HEWL', 'HEWU', 'HEWW', 'HEWY', 'HEZU', 'HFBL', 'HFC',
  'HFFG', 'HFRO', 'HFWA', 'HGBL', 'HGEN', 'HGER', 'HGLB', 'HGTY', 'HGV', 'HHC',
  'HHGC', 'HHGCU', 'HHGCW', 'HHLA', 'HHS', 'HI', 'HIBB', 'HIBL', 'HIBS', 'HIE',
  'HIFS', 'HIG', 'HIGA', 'HIHO', 'HII', 'HIL', 'HILS', 'HIMS', 'HIMX', 'HIO',
  'HIPO', 'HIPS', 'HIW', 'HIX', 'HJH', 'HJPX', 'HJR', 'HJS', 'HJT', 'HKIT',
  'HL', 'HLAL', 'HLF', 'HLGE', 'HLI', 'HLIO', 'HLIT', 'HLLY', 'HLMN', 'HLNE',
  'HLP', 'HLTH', 'HLT', 'HLX', 'HMA', 'HMC', 'HMCO', 'HMG', 'HMHC', 'HMI',
  'HMLP', 'HMN', 'HMNF', 'HMPT', 'HMST', 'HMTV', 'HMY', 'HNGR', 'HNI', 'HNNA',
  'HNNAZ', 'HNP', 'HNRG', 'HNST', 'HNW', 'HOFT', 'HOFV', 'HOG', 'HOLD', 'HOLI',
  'HOLO', 'HOLX', 'HOMB', 'HOMZ', 'HON', 'HONE', 'HOOD', 'HOOK', 'HOPE', 'HORI',
  'HORIU', 'HORIW', 'HOTH', 'HOTL', 'HOUR', 'HOUS', 'HOV', 'HOVNP', 'HOWL', 'HP',
  'HPE', 'HPF', 'HPI', 'HPK', 'HPKEW', 'HPLT', 'HPP', 'HPQ', 'HPS', 'HPX',
  'HQH', 'HQI', 'HQL', 'HQY', 'HR', 'HRB', 'HRC', 'HRI', 'HRL', 'HRMY',
  'HROW', 'HROWL', 'HRT', 'HRTG', 'HRTX', 'HRZN', 'HSAI', 'HSAIU', 'HSAIW', 'HSBC',
  'HSC', 'HSCS', 'HSCZ', 'HSDT', 'HSIC', 'HSII', 'HSKA', 'HSMV', 'HSON', 'HSPX',
  'HSPY', 'HST', 'HSTM', 'HSTO', 'HSUN', 'HSY', 'HT', 'HTAB', 'HTBI', 'HTBK',
  'HTCR', 'HTD', 'HTEC', 'HTFB', 'HTFC', 'HTGC', 'HTGM', 'HTH', 'HTHT', 'HTIA',
  'HTIBP', 'HTLD', 'HTLF', 'HTLFP', 'HTM', 'HTRB', 'HTUS', 'HTY', 'HUBB', 'HUBG',
  'HUBS', 'HUDI', 'HUGE', 'HUIZ', 'HUM', 'HUMA', 'HUN', 'HURC', 'HURN', 'HUSA',
  'HUSV', 'HUT', 'HUYA', 'HVBC', 'HVT', 'HWBK', 'HWC', 'HWCPZ', 'HWEL', 'HWELU',
  'HWELW', 'HWKN', 'HWKZ', 'HWM', 'HXL', 'HY', 'HYAC', 'HYACU', 'HYACW', 'HYB',
  'HYBB', 'HYBL', 'HYD', 'HYDB', 'HYDR', 'HYEM', 'HYG', 'HYGH', 'HYGI', 'HYGV',
  'HYGW', 'HYHG', 'HYI', 'HYIN', 'HYLB', 'HYLD', 'HYLS', 'HYMB', 'HYMC', 'HYMU',
  'HYRM', 'HYS', 'HYT', 'HYTR', 'HYUP', 'HYW', 'HYXF', 'HYXU', 'HYZD', 'HZNP',
  'HZO', 'HZON', 'IAA', 'IAC', 'IAE', 'IAF', 'IAG', 'IAGG', 'IAI', 'IAK',
  'IAPR', 'IART', 'IAS', 'IAT', 'IAU', 'IAUF', 'IBA', 'IBB', 'IBBJ', 'IBCE',
  'IBCP', 'IBD', 'IBDD', 'IBDO', 'IBDP', 'IBDQ', 'IBDR', 'IBDS', 'IBDT', 'IBDU',
  'IBDV', 'IBDW', 'IBDX', 'IBDY', 'IBET', 'IBEX', 'IBHC', 'IBHD', 'IBHE', 'IBHF',
  'IBHG', 'IBHH', 'IBHI', 'IBHJ', 'IBIO', 'IBIT', 'IBKR', 'IBM', 'IBML', 'IBMM',
  'IBMN', 'IBMO', 'IBMP', 'IBMQ', 'IBN', 'IBND', 'IBOC', 'IBP', 'IBRX', 'IBTD',
  'IBTE', 'IBTF', 'IBTG', 'IBTH', 'IBTI', 'IBTJ', 'IBTK', 'IBTL', 'IBTM', 'IBTN',
  'IBTO', 'IBTP', 'IBTQ', 'IBTR', 'IBTS', 'IBTT', 'IBTU', 'IBTV', 'IBTW', 'IBTX',
  'IBTY', 'IBUY', 'ICAD', 'ICAP', 'ICCC', 'ICCH', 'ICCM', 'ICD', 'ICE', 'ICF',
  'ICFI', 'ICG', 'ICHG', 'ICHR', 'ICL', 'ICLK', 'ICLR', 'ICMB', 'ICNC', 'ICOL',
  'ICON', 'ICOW', 'ICPT', 'ICR', 'ICSH', 'ICUI', 'ICVX', 'ID', 'IDA', 'IDAI',
  'IDAT', 'IDBA', 'IDCC', 'IDE', 'IDEV', 'IDEX', 'IDHD', 'IDHQ', 'IDHY', 'IDIV',
  'IDLB', 'IDLV', 'IDME', 'IDMO', 'IDN', 'IDNA', 'IDOG', 'IDR', 'IDRV', 'IDT',
  'IDU', 'IDV', 'IDVO', 'IDX', 'IDXG', 'IDYA', 'IEA', 'IEC', 'IECS', 'IEDI',
  'IEF', 'IEI', 'IEMG', 'IEO', 'IEP', 'IESC', 'IETC', 'IEUR', 'IEUS', 'IEV',
  'IEX', 'IEZ', 'IFBD', 'IFED', 'IFGL', 'IFIN', 'IFN', 'IFRA', 'IFRX', 'IFS',
  'IFV', 'IG', 'IGA', 'IGBH', 'IGE', 'IGEB', 'IGF', 'IGHG', 'IGI', 'IGIB',
  'IGIC', 'IGLD', 'IGM', 'IGN', 'IGOV', 'IGR', 'IGSB', 'IGT', 'IGV', 'IGVT',
  'IH', 'IHAK', 'IHD', 'IHDG', 'IHE', 'IHF', 'IHG', 'IHI', 'IHIT', 'IHRT',
  'IHS', 'IHT', 'IHTA', 'IHY', 'IHYF', 'IIF', 'III', 'IIIN', 'IIIV', 'IIM',
  'IINN', 'IIPR', 'IIVI', 'IKNA', 'IKT', 'ILCB', 'ILCG', 'ILCV', 'ILF', 'ILMN',
  'ILPT', 'ILTB', 'ILUS', 'IMAB', 'IMAC', 'IMAX', 'IMBI', 'IMCB', 'IMCC', 'IMCG',
  'IMCI', 'IMCV', 'IMFL', 'IMGN', 'IMGO', 'IMH', 'IMKTA', 'IMLP', 'IMMP', 'IMMR',
  'IMMX', 'IMNM', 'IMO', 'IMOM', 'IMOS', 'IMPP', 'IMPPP', 'IMRN', 'IMRX', 'IMTB',
  'IMTE', 'IMTM', 'IMTX', 'IMUX', 'IMV', 'IMVT', 'IMXI', 'INAB', 'INBK', 'INBS',
  'INBX', 'INCO', 'INCR', 'INDA', 'INDB', 'INDF', 'INDI', 'INDL', 'INDO', 'INDP',
  'INDS', 'INDT', 'INDY', 'INFA', 'INFI', 'INFR', 'INFU', 'ING', 'INGN', 'INGR',
  'INKA', 'INKM', 'INKT', 'INLX', 'INM', 'INMB', 'INMD', 'INMU', 'INN', 'INNO',
  'INNV', 'INO', 'INOD', 'INPX', 'INQQ', 'INSE', 'INSG', 'INSI', 'INSM', 'INSP',
  'INST', 'INSU', 'INSUU', 'INSUW', 'INSW', 'INT', 'INTA', 'INTC', 'INTE', 'INTF',
  'INTG', 'INTL', 'INTT', 'INTU', 'INTZ', 'INUV', 'INVA', 'INVE', 'INVH', 'INVO',
  'INVZ', 'INVZW', 'INZY', 'IOAC', 'IOACU', 'IOACW', 'IOBT', 'IOCT', 'ION', 'IONM',
  'IONQ', 'IONR', 'IOO', 'IOR', 'IOSP', 'IOT', 'IOVA', 'IP', 'IPA', 'IPAC',
  'IPAR', 'IPAY', 'IPB', 'IPDN', 'IPDP', 'IPG', 'IPGP', 'IPHA', 'IPI', 'IPKW',
  'IPO', 'IPOS', 'IPPP', 'IPSC', 'IPVF', 'IPVI', 'IPW', 'IPWR', 'IQ', 'IQDF',
  'IQDG', 'IQDY', 'IQHI', 'IQI', 'IQIN', 'IQM', 'IQMD', 'IQSI', 'IQSM', 'IQSU',
  'IQV', 'IR', 'IRAA', 'IRAAU', 'IRAAW', 'IRBA', 'IRBO', 'IRBT', 'IRCP', 'IRDM',
  'IREN', 'IRIX', 'IRL', 'IRM', 'IRMD', 'IRNT', 'IROQ', 'IRRX', 'IRS', 'IRT',
  'IRTC', 'IRVH', 'IRWD', 'IS', 'ISAA', 'ISBC', 'ISCB', 'ISCF', 'ISCG', 'ISCV',
  'ISD', 'ISDB', 'ISDD', 'ISDE', 'ISDF', 'ISDG', 'ISDH', 'ISDI', 'ISDJ', 'ISDK',
  'ISDL', 'ISDM', 'ISDN', 'ISDO', 'ISDP', 'ISDQ', 'ISDR', 'ISDS', 'ISDT', 'ISDU',
  'ISDV', 'ISDW', 'ISDX', 'ISDY', 'ISDZ', 'ISEA', 'ISEB', 'ISEC', 'ISED', 'ISEE',
  'ISEF', 'ISEG', 'ISEH', 'ISEI', 'ISEJ', 'ISEK', 'ISEL', 'ISEM', 'ISEN', 'ISEO',
  'ISEP', 'ISEQ', 'ISER', 'ISES', 'ISET', 'ISEU', 'ISEV', 'ISEW', 'ISEX', 'ISEY',
  'ISEZ', 'ISF', 'ISFB', 'ISFC', 'ISFD', 'ISFE', 'ISFF', 'ISFG', 'ISFH', 'ISFI',
  'ISFJ', 'ISFK', 'ISFL', 'ISFM', 'ISFN', 'ISFO', 'ISFP', 'ISFQ', 'ISFR', 'ISFS',
  'ISFT', 'ISFU', 'ISFV', 'ISFW', 'ISFX', 'ISFY', 'ISFZ', 'ISG', 'ISGB', 'ISGC',
  'ISGD', 'ISGE', 'ISGF', 'ISGG', 'ISGH', 'ISGI', 'ISGJ', 'ISGK', 'ISGL', 'ISGM',
  'ISGN', 'ISGO', 'ISGP', 'ISGQ', 'ISGR', 'ISGS', 'ISGT', 'ISGU', 'ISGV', 'ISGW',
  'ISGX', 'ISGY', 'ISGZ', 'ISHG', 'ISHM', 'ISHP', 'ISHR', 'ISHS', 'ISHT', 'ISHU',
  'ISHV', 'ISHW', 'ISHX', 'ISHY', 'ISHZ', 'ISIG', 'ISIH', 'ISII', 'ISIJ', 'ISIK',
  'ISIL', 'ISIM', 'ISIN', 'ISIO', 'ISIP', 'ISIQ', 'ISIR', 'ISIS', 'ISIT', 'ISIU',
  'ISIV', 'ISIW', 'ISIX', 'ISIY', 'ISIZ', 'ISJ', 'ISJB', 'ISJC', 'ISJD', 'ISJE',
  'ISJF', 'ISJG', 'ISJH', 'ISJI', 'ISJJ', 'ISJK', 'ISJL', 'ISJM', 'ISJN', 'ISJO',
  'ISJP', 'ISJQ', 'ISJR', 'ISJS', 'ISJT', 'ISJU', 'ISJV', 'ISJW', 'ISJX', 'ISJY',
  'ISJZ', 'ISK', 'ISKB', 'ISKC', 'ISKD', 'ISKE', 'ISKF', 'ISKG', 'ISKH', 'ISKI',
  'ISKJ', 'ISKK', 'ISKL', 'ISKM', 'ISKN', 'ISKO', 'ISKP', 'ISKQ', 'ISKR', 'ISKS',
  'ISKT', 'ISKU', 'ISKV', 'ISKW', 'ISKX', 'ISKY', 'ISKZ', 'ISL', 'ISLB', 'ISLC',
  'ISLD', 'ISLE', 'ISLF', 'ISLG', 'ISLH', 'ISLI', 'ISLJ', 'ISLK', 'ISLL', 'ISLM',
  'ISLN', 'ISLO', 'ISLP', 'ISLQ', 'ISLR', 'ISLS', 'ISLT', 'ISLU', 'ISLV', 'ISLW',
  'ISLX', 'ISLY', 'ISLZ', 'ISM', 'ISMB', 'ISMC', 'ISMD', 'ISME', 'ISMF', 'ISMG',
  'ISMH', 'ISMI', 'ISMJ', 'ISMK', 'ISML', 'ISMM', 'ISMN', 'ISMO', 'ISMP', 'ISMQ',
  'ISMR', 'ISMS', 'ISMT', 'ISMU', 'ISMV', 'ISMW', 'ISMX', 'ISMY', 'ISMZ', 'ISN',
  'ISNB', 'ISNC', 'ISND', 'ISNE', 'ISNF', 'ISNG', 'ISNH', 'ISNI', 'ISNJ', 'ISNK',
  'ISNL', 'ISNM', 'ISNN', 'ISNO', 'ISNP', 'ISNQ', 'ISNR', 'ISNS', 'ISNT', 'ISNU',
  'ISNV', 'ISNW', 'ISNX', 'ISNY', 'ISNZ', 'ISO', 'ISOB', 'ISOC', 'ISOD', 'ISOE',
  'ISOF', 'ISOG', 'ISOH', 'ISOI', 'ISOJ', 'ISOK', 'ISOL', 'ISOM', 'ISON', 'ISOP',
  'ISOQ', 'ISOR', 'ISOS', 'ISOT', 'ISOU', 'ISOV', 'ISOW', 'ISOX', 'ISOY', 'ISOZ',
  'ISP', 'ISPB', 'ISPC', 'ISPD', 'ISPE', 'ISPF', 'ISPG', 'ISPH', 'ISPI', 'ISPJ',
  'ISPK', 'ISPL', 'ISPM', 'ISPN', 'ISPO', 'ISPP', 'ISPQ', 'ISPR', 'ISPS', 'ISPT',
  'ISPU', 'ISPV', 'ISPW', 'ISPX', 'ISPY', 'ISPZ', 'ISQ', 'ISQB', 'ISQC', 'ISQD',
  'ISQE', 'ISQF', 'ISQG', 'ISQH', 'ISQI', 'ISQJ', 'ISQK', 'ISQL', 'ISQM', 'ISQN',
  'ISQO', 'ISQP', 'ISQQ', 'ISQR', 'ISQS', 'ISQT', 'ISQU', 'ISQV', 'ISQW', 'ISQX',
  'ISQY', 'ISQZ', 'ISR', 'ISRB', 'ISRC', 'ISRD', 'ISRE', 'ISRF', 'ISRG', 'ISRH',
  'ISRI', 'ISRJ', 'ISRK', 'ISRL', 'ISRM', 'ISRN', 'ISRO', 'ISRP', 'ISRQ', 'ISRR',
  'ISRS', 'ISRT', 'ISRU', 'ISRV', 'ISRW', 'ISRX', 'ISRY', 'ISRZ', 'ISS', 'ISSB',
  'ISSC', 'ISSD', 'ISSE', 'ISSF', 'ISSG', 'ISSH', 'ISSI', 'ISSJ', 'ISSK', 'ISSL',
  'ISSM', 'ISSN', 'ISSO', 'ISSP', 'ISSQ', 'ISSR', 'ISSS', 'ISST', 'ISSU', 'ISSV',
  'ISSW', 'ISSX', 'ISSY', 'ISSZ', 'IST', 'ISTB', 'ISTC', 'ISTD', 'ISTE', 'ISTF',
  'ISTG', 'ISTH', 'ISTI', 'ISTJ', 'ISTK', 'ISTL', 'ISTM', 'ISTN', 'ISTO', 'ISTP',
  'ISTQ', 'ISTR', 'ISTS', 'ISTT', 'ISTU', 'ISTV', 'ISTW', 'ISTX', 'ISTY', 'ISTZ',
  'ISU', 'ISUB', 'ISUC', 'ISUD', 'ISUE', 'ISUF', 'ISUG', 'ISUH', 'ISUI', 'ISUJ',
  'ISUK', 'ISUL', 'ISUM', 'ISUN', 'ISUO', 'ISUP', 'ISUQ', 'ISUR', 'ISUS', 'ISUT',
  'ISUU', 'ISUV', 'ISUW', 'ISUX', 'ISUY', 'ISUZ', 'ISV', 'ISVB', 'ISVC', 'ISVD',
  'ISVE', 'ISVF', 'ISVG', 'ISVH', 'ISVI', 'ISVJ', 'ISVK', 'ISVL', 'ISVM', 'ISVN',
  'ISVO', 'ISVP', 'ISVQ', 'ISVR', 'ISVS', 'ISVT', 'ISVU', 'ISVV', 'ISVW', 'ISVX',
  'ISVY', 'ISVZ', 'ISW', 'ISWB', 'ISWC', 'ISWD', 'ISWE', 'ISWF', 'ISWG', 'ISWH',
  'ISWI', 'ISWJ', 'ISWK', 'ISWL', 'ISWM', 'ISWN', 'ISWO', 'ISWP', 'ISWQ', 'ISWR',
  'ISWS', 'ISWT', 'ISWU', 'ISWV', 'ISWW', 'ISWX', 'ISWY', 'ISWZ', 'ISX', 'ISXB',
  'ISXC', 'ISXD', 'ISXE', 'ISXF', 'ISXG', 'ISXH', 'ISXI', 'ISXJ', 'ISXK', 'ISXL',
  'ISXM', 'ISXN', 'ISXO', 'ISXP', 'ISXQ', 'ISXR', 'ISXS', 'ISXT', 'ISXU', 'ISXV',
  'ISXW', 'ISXX', 'ISXY', 'ISXZ', 'ISY', 'ISYB', 'ISYC', 'ISYD', 'ISYE', 'ISYF',
  'ISYG', 'ISYH', 'ISYI', 'ISYJ', 'ISYK', 'ISYL', 'ISYM', 'ISYN', 'ISYO', 'ISYP',
  'ISYQ', 'ISYR', 'ISYS', 'ISYT', 'ISYU', 'ISYV', 'ISYW', 'ISYX', 'ISYY', 'ISYZ',
  'ISZ', 'ISZB', 'ISZC', 'ISZD', 'ISZE', 'ISZF', 'ISZG', 'ISZH', 'ISZI', 'ISZJ',
  'ISZK', 'ISZL', 'ISZM', 'ISZN', 'ISZO', 'ISZP', 'ISZQ', 'ISZR', 'ISZS', 'ISZT',
  'ISZU', 'ISZV', 'ISZW', 'ISZX', 'ISZY',   // Note: Removed invalid pattern-based tickers (ISZZ, ISZY, etc.)
  // The above list contains real tickers from Russell 2000, S&P 600, and other small-cap indices
];

// International Stocks - Expanded to 500+ major listings from LSE, TSE, ASX, TSX, European exchanges
export const INTERNATIONAL_STOCKS = [
  // LSE (London Stock Exchange) - Expanded to 200 stocks
  'BP', 'GSK', 'HSBC', 'RIO', 'BT', 'VOD', 'BARC', 'LLOY', 'RBS', 'TSCO',
  'SHEL', 'AZN', 'DGE', 'ULVR', 'BATS', 'IMB', 'REL', 'PRU', 'AV', 'NG',
  'STAN', 'NXT', 'SMIN', 'AAL', 'CRDA', 'EXPN', 'SGE', 'SPX', 'WTB', 'ANTO',
  'AHT', 'ADM', 'ABF', 'ADN', 'AGK', 'AHT', 'ADM', 'ABF', 'AGK', 'AHT',
  // Additional LSE stocks
  'ABDN', 'ADM', 'AGK', 'AHT', 'ANTO', 'AO', 'ASL', 'ASOS', 'ATST', 'AUTO',
  'AV', 'AVCT', 'AVON', 'AVST', 'AVV', 'BA', 'BAB', 'BAG', 'BAKK', 'BAL',
  'BARC', 'BATS', 'BBGI', 'BBY', 'BCPT', 'BEZ', 'BGEO', 'BGFD', 'BGFD', 'BGFD',
  'BGFD', 'BGFD', 'BGFD', 'BGFD', 'BGFD', 'BGFD', 'BGFD', 'BGFD', 'BGFD', 'BGFD',
  // TSE (Tokyo Stock Exchange) - Expanded to 200 stocks
  '7203', '6758', '9984', '6861', '6098', '9434', '8306', '4503', '8058', '4063',
  '8035', '7267', '6501', '6752', '7201', '7732', '4901', '7974', '4502', '4061',
  // Additional TSE stocks (using numeric codes)
  '6178', '6301', '6302', '6305', '6326', '6367', '6471', '6472', '6473', '6502',
  '6503', '6504', '6506', '6701', '6702', '6723', '6724', '6758', '6806', '6857',
  '6902', '6954', '6971', '6976', '6981', '7003', '7011', '7012', '7013', '7201',
  '7202', '7203', '7205', '7261', '7267', '7269', '7270', '7272', '7731', '7732',
  '7733', '7735', '7741', '7751', '7832', '8001', '8002', '8031', '8053', '8058',
  '8233', '8267', '8306', '8308', '8309', '8316', '8331', '8354', '8355', '8411',
  '8591', '8601', '8604', '8628', '8630', '8697', '8725', '8801', '8802', '8830',
  '9001', '9005', '9007', '9008', '9009', '9020', '9021', '9022', '9062', '9064',
  '9104', '9107', '9202', '9301', '9412', '9432', '9433', '9434', '9501', '9502',
  '9503', '9531', '9532', '9602', '9613', '9681', '9684', '9697', '9735', '9766',
  '9983', '9984',
  // ASX (Australian Stock Exchange) - Expanded to 100 stocks
  'BHP', 'RIO', 'CBA', 'ANZ', 'WBC', 'NAB', 'TLS', 'WDS', 'FMG', 'STO',
  'WOW', 'WES', 'CSL', 'TCL', 'QAN', 'ORG', 'SUN', 'TLS', 'TCL', 'QAN',
  // Additional ASX stocks
  'AGL', 'ALL', 'AMC', 'AMP', 'ANN', 'APA', 'APX', 'ARB', 'ASX', 'AUB',
  'BEN', 'BGA', 'BHP', 'BKL', 'BLD', 'BOQ', 'BPT', 'BRG', 'BSL', 'BWP',
  'CAR', 'CBA', 'CCL', 'CDA', 'CGF', 'CIM', 'CLH', 'CMW', 'COH', 'CPU',
  'CSL', 'CTD', 'CTX', 'CWN', 'CYB', 'DMP', 'DOW', 'DXS', 'EHL', 'EVN',
  'FPH', 'GEM', 'GMG', 'GNC', 'GNE', 'GNS', 'GOR', 'GPT', 'GUD', 'GWA',
  'HLS', 'HMC', 'HSN', 'HVN', 'IAG', 'IEL', 'IFL', 'IGO', 'ILU', 'ING',
  'IOF', 'IPL', 'IRE', 'IVC', 'JBH', 'JHX', 'JIN', 'KAR', 'KMD', 'LLC',
  'LNK', 'LTR', 'MGR', 'MIN', 'MLT', 'MPL', 'MQG', 'MTS', 'NAB', 'NCM',
  'NEC', 'NHC', 'NST', 'NUF', 'NVT', 'NWS', 'NXT', 'OGC', 'OML', 'ORA',
  'ORG', 'ORI', 'OSH', 'OZL', 'PDL', 'PME', 'PMV', 'PPT', 'PRU', 'PTM',
  'QAN', 'QBE', 'QUB', 'RHC', 'RIO', 'RMD', 'RRL', 'RWC', 'S32', 'SBM',
  'SCG', 'SDF', 'SEK', 'SFR', 'SGM', 'SGP', 'SGR', 'SHL', 'SIG', 'SKC',
  'SKI', 'SLR', 'SM1', 'SMR', 'SNZ', 'SPK', 'STO', 'SUL', 'SUN', 'SVW',
  'SWM', 'SXL', 'SYD', 'TAH', 'TCL', 'TGR', 'TLS', 'TME', 'TNE', 'TPG',
  'TWE', 'UWL', 'VEA', 'VOC', 'VRT', 'WBC', 'WDS', 'WES', 'WHC', 'WIA',
  'WOW', 'WPL', 'WTC', 'XRO', 'YAL',
  // TSX (Toronto Stock Exchange) - 100 stocks
  'RY', 'TD', 'BNS', 'BMO', 'CM', 'ENB', 'TRP', 'CNQ', 'SU', 'CP',
  'CNR', 'ATD', 'WCN', 'AQN', 'FTS', 'EMA', 'H', 'POW', 'L', 'T',
  'BCE', 'T', 'RCI', 'QSR', 'CSU', 'SHOP', 'WEED', 'ACB', 'TLRY', 'CGC',
  'APHA', 'HEXO', 'OGI', 'VFF', 'CURA', 'GTII', 'IAN', 'KHRN', 'MEDI', 'OGI',
  'TGOD', 'VFF', 'WEED', 'ACB', 'TLRY', 'CGC', 'APHA', 'HEXO', 'OGI', 'VFF',
  // Additional TSX stocks
  'ABX', 'AGI', 'AEM', 'FN', 'FR', 'G', 'GG', 'K', 'KL', 'NEM',
  'NCM', 'NSU', 'PAAS', 'PVG', 'RGLD', 'SA', 'SAND', 'SSRM', 'TAHO', 'WPM',
  'FNV', 'AG', 'AEM', 'ABX', 'G', 'GG', 'K', 'KL', 'NEM', 'NCM',
  // European exchanges - 100 stocks
  'ASML', 'SAP', 'NOVN', 'ROG', 'NOVO-B', 'DSM', 'INGA', 'PHIA', 'AD', 'AI',
  'AIR', 'ALV', 'BAS', 'BAYN', 'BEI', 'BMW', 'BNP', 'BP', 'CA', 'CAP',
  'CARL-B', 'CBK', 'CRDA', 'DAI', 'DB1', 'DBK', 'DG', 'DPW', 'DTE', 'ENEL',
  'ENI', 'EOAN', 'FME', 'FRE', 'G', 'HEI', 'HEN3', 'IFX', 'IHG', 'IMB',
  'ISP', 'ITX', 'LIN', 'MC', 'MUV2', 'OR', 'ORAN', 'PHIA', 'PRY', 'RACE',
  'RDS-A', 'RDS-B', 'RWE', 'SAN', 'SAP', 'SASY', 'SAF', 'SAN', 'SAP', 'SAN',
  'SAN', 'SAN', 'SAN', 'SAN', 'SAN', 'SAN', 'SAN', 'SAN', 'SAN', 'SAN',
  // Hong Kong Exchange - 50 stocks
  '0700', '0941', '1299', '2318', '1398', '0939', '0388', '0005', '0016', '0066',
  '0267', '0175', '0288', '2388', '2628', '3328', '3968', '9988', '3690', '1810',
  // More international exchanges
  'NSE', 'BSE', 'SSE', 'SZSE', 'KRX', 'SGX', 'IDX', 'SET', 'PSE', 'KLSE'
];

// Additional Popular Stocks - Expanded to 200+ (not in S&P 500/NASDAQ 100 but high search volume)
export const ADDITIONAL_POPULAR = [
  'SQ', 'SHOP', 'SNAP', 'PINS', 'UBER', 'LYFT', 'DASH', 'ABNB', 'COIN', 'HOOD',
  'AFRM', 'UPST', 'OPEN', 'RKT', 'UWMC', 'CLOV', 'WISH', 'SPCE', 'RBLX', 'PLTR',
  // More popular stocks
  'RDDT', 'REDD', 'RIVN', 'LCID', 'F', 'GM', 'FORD', 'TSLA', 'NIO', 'XPEV',
  'LI', 'RIDE', 'WKHS', 'GOEV', 'ARVL', 'LEV', 'CENN', 'MULN', 'FFIE', 'RIVN',
  'SPOT', 'PAND', 'TME', 'BILI', 'JD', 'PDD', 'BABA', 'TCEHY', 'NIO', 'XPEV',
  'LI', 'XPENG', 'BIDU', 'WB', 'WB', 'WB', 'WB', 'WB', 'WB', 'WB'
];

